<a href="https://colab.research.google.com/github/mybenkhadda/GEMS---drivendata/blob/main/notebooks/colab/00_setup_and_drive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00 · Setup: Drive, package, GPU, paths, manifests

**GitHub = code · Colab `/content` = fast ephemeral execution · Google Drive (`MyDrive/GEMS_2`) = persistent data and artifacts.**

Run this notebook at the start of every Colab session (or copy its first cell into any other notebook: every notebook here starts with the same idempotent bootstrap).

1. Mount Drive · 2. clone the repository at a pinned commit and `pip install -e .[colab]` · 3. check PyTorch / GPU · 4. record package version + commit · 5. free disk / VRAM · 6. validate data paths · 7. create the workspace folders · 8. stage the core data from Drive to `/content/gems_work` · 9. reload experiment manifests · 10. environment report.

Nothing here trains a model. No credentials are stored in the notebook: a private repository is cloned with a token read from Colab *Secrets* (`GITHUB_TOKEN`).

In [1]:
# --- session bootstrap (idempotent; identical in notebooks 00-07) ---------------------------------
REPO = 'mybenkhadda/GEMS---drivendata'          # GitHub owner/name of this project
COMMIT = 'main'                    # pin a commit SHA for reproducible experiments
DRIVE_ROOT = '/content/drive/MyDrive/GEMS_2'
import os, subprocess, sys
from google.colab import drive
drive.mount('/content/drive')
token = ''
try:
    from google.colab import userdata
    token = userdata.get('GITHUB_TOKEN') or ''
except Exception:
    pass
url = f'https://github.com/{REPO}.git'   # token-free remote: a token never goes into the URL / .git/config
# private fork only: GITHUB_TOKEN (Colab Secret) is sent as an HTTP header through env vars, per command
genv = {**os.environ, 'GIT_CONFIG_COUNT': '1', 'GIT_CONFIG_KEY_0': 'http.https://github.com/.extraheader', 'GIT_CONFIG_VALUE_0': 'AUTHORIZATION: basic ' + __import__('base64').b64encode(f'x-access-token:{token}'.encode()).decode()} if token else None
if not os.path.exists('/content/GEMS/.git'):
    subprocess.run(['git', 'clone', '-q', url, '/content/GEMS'], check=True, env=genv)
subprocess.run(['git', '-C', '/content/GEMS', 'remote', 'set-url', 'origin', url], check=True)  # drop an old embedded token
subprocess.run(['git', '-C', '/content/GEMS', 'fetch', '-q', 'origin'], check=True, env=genv)
subprocess.run(['git', '-C', '/content/GEMS', 'checkout', '-q', COMMIT], check=True)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '-e', '/content/GEMS[colab]'], check=True)
if '/content/GEMS' not in sys.path:
    sys.path.insert(0, '/content/GEMS')       # editable install is not visible to an already-running kernel
from gems_bench.runtime import colab
colab.configure(drive_root=DRIVE_ROOT)
print(subprocess.run(['git', '-C', '/content/GEMS', 'rev-parse', 'HEAD'], capture_output=True, text=True).stdout)

Mounted at /content/drive
32c0ad518fc375fdd872424a2a78503d54def93f

## Download and organize the data (once)

DrivenData links are **personal and expire**. Log in, open the competition's *Data download* page, copy each file's link and paste it into `DATA` below. If the data comes as one zip, paste its link into `ARCHIVE_URL` instead.

Each file is fetched with `wget -c` (resumable) to the fast local disk. It is then checked (it must open as a GeoTIFF, and its size is compared with the known release), moved into the workspace layout (`data/raw/geodawn`, `data/raw/faults`) and copied to Drive with a checksum.

Files already on Drive are skipped, so re-running this cell is harmless. Never commit or share the links.

The second cell optionally lists the USGS 1 m DEM products for the study area with `wget` (metadata only; no tiles).

The legacy Phase 1–4 `outputs/` (feature caches, folds, model maps) are not downloadable: upload them once from the local project (`docs/GOOGLE_DRIVE_LAYOUT.md`).

In [2]:

# ============================================================
# GEMS 2.0 — One-time persistent data collection
# DrivenData GeoDAWN + labels + submission + USGS 1m DEM
#
# Download once -> verify -> Google Drive -> reuse forever
#
# Requires: requests, rasterio
# ============================================================

import os
import json
import time
import shutil
import hashlib
import logging
from pathlib import Path
from urllib.parse import urlsplit, unquote
from datetime import datetime, timezone

import requests
import rasterio
import pandas as pd

# ------------------------------------------------------------
# 1. CONFIGURATION
# ------------------------------------------------------------

LOCAL = Path(colab.LOCAL_ROOT).resolve()
DRIVE = Path(DRIVE_ROOT).resolve()

# Full download can be large. Set to an integer for a pilot.
MAX_DEM_TILES = None  # None = download all DEM URLs
DOWNLOAD_DEM = True

# Re-hash existing Drive files on every run (slower but stricter)
VERIFY_EXISTING_SHA = False

CHUNK_BYTES = 8 * 1024 * 1024
MAX_RETRIES = 5

DATA_ROOT = Path("data/raw")
DEM_ROOT = DATA_ROOT / "dem_1m"
MANIFEST_PATH = DRIVE / "data/manifests/download_manifest.json"

# ------------------------------------------------------------
# 2. OFFICIAL COMPETITION FILES
# ------------------------------------------------------------

def _url(secret):
    """Signed DrivenData link from Colab Secrets (key icon). Links expire: never paste them into a cell."""
    try:
        from google.colab import userdata
        return userdata.get(secret) or f"MISSING-COLAB-SECRET-{secret}"
    except Exception:                 # only used when the file is absent on Drive
        return f"MISSING-COLAB-SECRET-{secret}"

DATA = {
    "data/raw/geodawn/gems-geodawn-numerical-features.tif": (
        _url("GEMS_URL_FEATURES"),
        418_912_844,
    ),
    "data/raw/faults/existing_faults.tif": (
        _url("GEMS_URL_FAULTS"),
        425_830,
    ),
    "data/raw/example_submission.tif": (
        _url("GEMS_URL_SUBMISSION"),
        1_599_597,
    ),
}

TNM_JSON_URL = _url("GEMS_URL_DEM_JSON")

JSON_REL = DATA_ROOT / "tnm_items.json"

# ------------------------------------------------------------
# 3. LOGGING + MANIFEST
# ------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    force=True,
)
log = logging.getLogger("GEMS_DOWNLOAD")

LOCAL.mkdir(parents=True, exist_ok=True)
DRIVE.mkdir(parents=True, exist_ok=True)
MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)

if MANIFEST_PATH.exists():
    try:
        manifest = json.loads(MANIFEST_PATH.read_text())
    except (ValueError, OSError):
        raise RuntimeError(
            "Download manifest is unreadable. "
            "Inspect it before continuing."
        )
else:
    manifest = {"version": 1, "files": {}}


def utc_now():
    return datetime.now(timezone.utc).isoformat()


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(CHUNK_BYTES), b""):
            digest.update(chunk)
    return digest.hexdigest()


def save_manifest():
    temp = MANIFEST_PATH.with_name(MANIFEST_PATH.name + ".tmp")
    temp.write_text(json.dumps(manifest, indent=2))
    temp.replace(MANIFEST_PATH)


def validate_file(path, expected=None, is_tif=True):
    if not path.is_file() or path.stat().st_size == 0:
        raise ValueError(f"Missing or empty file: {path}")

    size = path.stat().st_size

    if expected is not None and size != expected:
        log.warning(
            "%s: size %s differs from reference %s",
            path.name, size, expected,
        )

    if is_tif:
        with rasterio.open(path) as src:
            if src.count <= 0 or src.width <= 0 or src.height <= 0:
                raise ValueError(f"Invalid raster dimensions: {path}")

            # Read a small window to detect some corrupt TIFFs.
            src.read(
                1,
                window=((0, min(1, src.height)),
                        (0, min(1, src.width))),
            )

    else:
        with open(path, "r", encoding="utf-8") as f:
            json.load(f)

    return size


# ------------------------------------------------------------
# 4. RESUMABLE HTTP DOWNLOAD
# ------------------------------------------------------------

session = requests.Session()
session.headers.update({"User-Agent": "GEMS-Research-Downloader/1.0"})


def download_resumable(url, destination):
    destination.parent.mkdir(parents=True, exist_ok=True)
    partial = destination.with_name(destination.name + ".partial")

    for attempt in range(1, MAX_RETRIES + 1):
        offset = partial.stat().st_size if partial.exists() else 0

        headers = {"Range": f"bytes={offset}-"} if offset else {}

        try:
            with session.get(
                url,
                headers=headers,
                stream=True,
                timeout=(30, 120),
                allow_redirects=True,
            ) as response:

                if response.status_code in (401, 403):
                    raise PermissionError(
                        f"Access denied for {destination.name}. "
                        "A signed DrivenData link may have expired."
                    )

                if response.status_code == 416 and offset:
                    # The existing partial may already contain the
                    # whole remote file. Validate it below.
                    response.close()
                    if destination.suffix.lower() in (".tif", ".tiff"):
                        validate_file(partial, is_tif=True)
                    else:
                        validate_file(partial, is_tif=False)
                    partial.replace(destination)
                    return destination

                response.raise_for_status()

                # Server ignored Range: restart instead of appending.
                mode = "ab"
                if offset == 0 or response.status_code == 200:
                    mode = "wb"

                if offset and response.status_code == 206:
                    content_range = response.headers.get("Content-Range", "")
                    if not content_range.startswith(f"bytes {offset}-"):
                        raise IOError(
                            f"Unexpected Content-Range: {content_range}"
                        )

                with open(partial, mode) as f:
                    for chunk in response.iter_content(
                        chunk_size=CHUNK_BYTES
                    ):
                        if chunk:
                            f.write(chunk)

            # Verify against Content-Length / Content-Range where possible.
            if response.status_code == 206:
                content_range = response.headers.get("Content-Range", "")
                total_text = content_range.rsplit("/", 1)[-1]
                remote_total = (
                    int(total_text) if total_text.isdigit() else None
                )
            else:
                length = response.headers.get("Content-Length")
                remote_total = int(length) if length else None

            if remote_total is not None:
                actual = partial.stat().st_size
                if actual != remote_total:
                    raise IOError(
                        f"Incomplete download: {actual}/{remote_total} bytes"
                    )

            if destination.suffix.lower() in (".tif", ".tiff"):
                validate_file(partial, is_tif=True)
            else:
                validate_file(partial, is_tif=False)

            partial.replace(destination)
            return destination

        except PermissionError:
            raise

        except Exception as exc:
            log.warning(
                "Attempt %d/%d failed for %s: %s",
                attempt, MAX_RETRIES, destination.name, exc,
            )
            if attempt == MAX_RETRIES:
                raise
            time.sleep(min(2 ** attempt, 30))

    raise RuntimeError(f"Download failed: {destination.name}")


# ------------------------------------------------------------
# 5. VERIFY + PERSIST TO GOOGLE DRIVE
# ------------------------------------------------------------

def collect_file(relative_path, url, expected=None, is_tif=True):
    rel = Path(relative_path)
    local_path = LOCAL / rel
    drive_path = DRIVE / rel

    key = rel.as_posix()
    previous = manifest["files"].get(key, {})

    # Drive is the persistent source of truth.
    if drive_path.exists():
        try:
            size = validate_file(drive_path, expected, is_tif)

            if VERIFY_EXISTING_SHA and previous.get("sha256"):
                digest = sha256_file(drive_path)
                if digest != previous["sha256"]:
                    raise ValueError("Existing Drive checksum mismatch")

            log.info("ON DRIVE | %s (%0.2f MB)", key, size / 1e6)

            if key not in manifest["files"]:
                manifest["files"][key] = {
                    "size_bytes": size,
                    "sha256": sha256_file(drive_path),
                    "verified_at": utc_now(),
                    "status": "ready",
                }
                save_manifest()

            return drive_path

        except Exception as exc:
            log.warning("Invalid Drive copy: %s: %s", key, exc)
            # Do not overwrite a questionable permanent copy silently.
            raise RuntimeError(
                f"Please inspect invalid Drive artifact: {drive_path}"
            ) from exc

    # Download into Colab's local working directory.
    if local_path.exists():
        try:
            validate_file(local_path, expected, is_tif)
            log.info("LOCAL CACHE | %s", key)
        except Exception:
            local_path.unlink()

    if not local_path.exists():
        log.info("DOWNLOADING | %s", key)
        download_resumable(url, local_path)

    size = validate_file(local_path, expected, is_tif)
    digest = sha256_file(local_path)

    # Copy to a temporary Drive file, then verify and rename.
    drive_path.parent.mkdir(parents=True, exist_ok=True)

    drive_partial = drive_path.with_name(drive_path.name + ".partial")

    if drive_partial.exists():
        drive_partial.unlink()

    shutil.copyfile(local_path, drive_partial)

    if (
        drive_partial.stat().st_size != size
        or sha256_file(drive_partial) != digest
    ):
        raise IOError(f"Drive transfer verification failed: {key}")

    drive_partial.replace(drive_path)

    manifest["files"][key] = {
        "size_bytes": size,
        "sha256": digest,
        "verified_at": utc_now(),
        "status": "ready",
    }
    save_manifest()

    log.info("SAVED TO DRIVE | %s (%0.2f MB)", key, size / 1e6)

    # Local copy is disposable after verified persistence.
    local_path.unlink(missing_ok=True)

    return drive_path


# ------------------------------------------------------------
# 6. COLLECT OFFICIAL DATA
# ------------------------------------------------------------

for rel, (url, expected) in DATA.items():
    collect_file(
        relative_path=rel,
        url=url,
        expected=expected,
        is_tif=True,
    )


# ------------------------------------------------------------
# 7. COLLECT USGS DEM URL JSON
# ------------------------------------------------------------

json_path = collect_file(
    relative_path=JSON_REL,
    url=TNM_JSON_URL,
    expected=None,
    is_tif=False,
)

with open(json_path, "r", encoding="utf-8") as f:
    tnm_data = json.load(f)

# Accept the list-of-URLs format shown in the competition.
if isinstance(tnm_data, list):
    dem_urls = [
        item if isinstance(item, str) else item.get("url")
        for item in tnm_data
        if isinstance(item, (str, dict))
    ]
elif isinstance(tnm_data, dict):
    items = tnm_data.get("items", tnm_data.get("urls", []))
    dem_urls = [
        item if isinstance(item, str) else item.get("url")
        for item in items
        if isinstance(item, (str, dict))
    ]
else:
    raise ValueError("Unsupported tnm_items.json structure")

dem_urls = list(dict.fromkeys(
    url for url in dem_urls
    if isinstance(url, str) and url.startswith("https://")
))

log.info("DEM URLs found: %d", len(dem_urls))


# ------------------------------------------------------------
# 8. PRESERVE PROJECT IDENTITY FOR OVERLAPPING DEM TILES
# ------------------------------------------------------------

def dem_relative_path(url):
    path = unquote(urlsplit(url).path)
    parts = Path(path).parts

    if "Projects" not in parts:
        raise ValueError(f"Unknown USGS tile URL structure: {url}")

    project_idx = parts.index("Projects")
    project = parts[project_idx + 1]
    filename = parts[-1]

    if not filename.lower().endswith((".tif", ".tiff")):
        raise ValueError(f"Not a GeoTIFF: {filename}")

    if project in ("", ".", "..") or "/" in project or "\\" in project:
        raise ValueError(f"Unsafe DEM project name: {project}")

    if filename in ("", ".", ".."):
        raise ValueError("Unsafe DEM filename")

    return DEM_ROOT / project / filename


dem_records = []
seen_paths = {}

for url in dem_urls:
    rel = dem_relative_path(url)
    key = rel.as_posix()

    if key in seen_paths and seen_paths[key] != url:
        raise ValueError(f"Different URLs map to the same path: {key}")

    seen_paths[key] = url
    dem_records.append({
        "project": rel.parent.name,
        "filename": rel.name,
        "relative_path": key,
        "url": url,
    })

dem_inventory = pd.DataFrame(dem_records)

inventory_path = DRIVE / "data/manifests/dem_url_inventory.csv"
inventory_path.parent.mkdir(parents=True, exist_ok=True)

dem_inventory.to_csv(inventory_path, index=False)

print("\nUSGS DEM projects:")
print(dem_inventory.groupby("project").size().to_string())

print("\nTotal DEM tiles:", len(dem_inventory))
print("Inventory:", inventory_path)


# ------------------------------------------------------------
# 9. ONE-TIME DEM DOWNLOADS
# ------------------------------------------------------------

if DOWNLOAD_DEM:
    selected = dem_records
    if MAX_DEM_TILES is not None:
        selected = selected[:MAX_DEM_TILES]

    successes = 0
    failures = []

    for i, item in enumerate(selected, start=1):
        print(f"\nDEM {i}/{len(selected)}: {item['filename']}")

        try:
            collect_file(
                relative_path=item["relative_path"],
                url=item["url"],
                expected=None,
                is_tif=True,
            )
            successes += 1
        except Exception as exc:
            failures.append({
                "relative_path": item["relative_path"],
                "error": str(exc),
            })
            log.error("FAILED | %s | %s", item["filename"], exc)

    print("\nDEM downloaded/reused:", successes)
    print("DEM failures:", len(failures))

    if failures:
        failure_path = DRIVE / "data/manifests/dem_failures.csv"
        pd.DataFrame(failures).to_csv(failure_path, index=False)
        print("Failure report:", failure_path)

else:
    print("DEM download disabled; inventory saved only.")


# ------------------------------------------------------------
# 10. SUMMARY
# ------------------------------------------------------------

summary = pd.DataFrame([
    {
        "path": key,
        "size_gb": round(item["size_bytes"] / 1024**3, 4),
        "status": item["status"],
        "sha256": item["sha256"],
    }
    for key, item in manifest["files"].items()
])

summary_path = DRIVE / "data/manifests/download_summary.csv"
summary.to_csv(summary_path, index=False)

print("\nDATA COLLECTION COMPLETE")
print("Drive root:", DRIVE)
print("Total cached files:", len(summary))
print("Total cached GB:", round(summary["size_gb"].sum(), 2))
print("Manifest:", MANIFEST_PATH)

2026-10-21 23:40:05,835 | INFO | ON DRIVE | data/raw/geodawn/gems-geodawn-numerical-features.tif (418.91 MB)
2026-10-21 23:40:06,434 | INFO | ON DRIVE | data/raw/faults/existing_faults.tif (0.43 MB)
2026-10-21 23:40:06,896 | INFO | ON DRIVE | data/raw/example_submission.tif (1.60 MB)
2026-10-21 23:40:07,357 | INFO | ON DRIVE | data/raw/tnm_items.json (0.15 MB)
2026-10-21 23:40:07,367 | INFO | DEM URLs found: 894

USGS DEM projects:
project
CA_SierraNevada_B22                  22
NV_EastCentral_2021_D21             141
NV_Humboldt_2021_D21                 15
NV_NorthWestElko_2020_D20            73
NV_Reno_Carson_QL1_2017              16
NV_Reno_Carson_QL2_2017              34
NV_UpperHumboldt_2016                 3
NV_WestCentral_EarthMRI_2020_D20    590

Total DEM tiles: 894
Inventory: /content/drive/MyDrive/GEMS_2/data/manifests/dem_url_inventory.csv

DEM 1/894: USGS_1M_10_x75y441_CA_SierraNevada_B22.tif

2026-10-21 23:40:10,331 | INFO | ON DRIVE | data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_10_x75y441_CA_SierraNevada_B22.tif (238.66 MB)

DEM 2/894: USGS_1M_10_x75y441_NV_WestCentral_EarthMRI_2020_D20.tif

2026-10-21 23:40:11,792 | INFO | ON DRIVE | data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_10_x75y441_NV_WestCentral_EarthMRI_2020_D20.tif (189.38 MB)

DEM 3/894: USGS_1M_10_x75y442_CA_SierraNevada_B22.tif

2026-10-21 23:40:13,477 | INFO | ON DRIVE | data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_10_x75y442_CA_SierraNevada_B22.tif (229.82 MB)

DEM 4/894: USGS_1M_10_x75y442_NV_WestCentral_EarthMRI_2020_D20.tif

2026-10-21 23:40:15,297 | INFO | ON DRIVE | data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_10_x75y442_NV_WestCentral_EarthMRI_2020_D20.tif (208.49 MB)

DEM 5/894: USGS_1M_10_x75y443_CA_SierraNevada_B22.tif

2026-10-21 23:40:16,721 | INFO | ON DRIVE | data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_10_x75y443_CA_SierraNevada_B22.tif (175.51 MB)

DEM 6/894: USGS_1M_10_x75y443_NV_WestCentral_EarthMRI_2020_D20.tif

2026-10-21 23:40:18,902 | INFO | ON DRIVE | data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_10_x75y443_NV_WestCentral_EarthMRI_2020_D20.tif (274.87 MB)

DEM 7/894: USGS_1M_10_x75y444_CA_SierraNevada_B22.tif

2026-10-21 23:40:20,794 | INFO | ON DRIVE | data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_10_x75y444_CA_SierraNevada_B22.tif (157.95 MB)

DEM 8/894: USGS_1M_10_x75y444_NV_WestCentral_EarthMRI_2020_D20.tif

2026-10-21 23:41:19,831 | INFO | GDAL signalled an error: err_no=1, msg='TIFFFillTile:Read error at row 4294967295, col 4294967295, tile 0; got 0 bytes, expected 537114'
2026-10-21 23:41:19,854 | INFO | GDAL signalled an error: err_no=1, msg='TIFFReadEncodedTile() failed.'
2026-10-21 23:41:19,860 | INFO | GDAL signalled an error: err_no=1, msg='USGS_1M_10_x75y444_NV_WestCentral_EarthMRI_2020_D20.tif, band 1: IReadBlock failed at X offset 0, Y offset 0: TIFFReadEncodedTile() failed.'
2026-10-21 23:41:19,864 | INFO | GDAL signalled an error: err_no=3, msg='USGS_1M_10_x75y444_NV_WestCentral_EarthMRI_2020_D20.tif: I/O error'
2026-10-21 23:41:19,866 | WARNING | Invalid Drive copy: data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_10_x75y444_NV_WestCentral_EarthMRI_2020_D20.tif: Read failed. See previous exception for details.
2026-10-21 23:41:19,869 | ERROR | FAILED | USGS_1M_10_x75y444_NV_WestCentral_EarthMRI_2020_D20.tif | Please inspect invalid Drive artifact: /content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_10_x75y444_NV_WestCentral_EarthMRI_2020_D20.tif
2026-10-21 23:41:19,873 | ERROR | FAILED | USGS_1M_10_x75y445_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_10_x75y445_CA_SierraNevada_B22.tif'
2026-10-21 23:41:19,874 | ERROR | FAILED | USGS_1M_10_x75y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_10_x75y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,877 | ERROR | FAILED | USGS_1M_10_x76y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_10_x76y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,880 | ERROR | FAILED | USGS_1M_10_x76y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_10_x76y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,881 | ERROR | FAILED | USGS_1M_10_x76y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_10_x76y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,883 | ERROR | FAILED | USGS_1M_10_x76y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_10_x76y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,885 | ERROR | FAILED | USGS_1M_10_x76y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_10_x76y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,888 | ERROR | FAILED | USGS_1M_10_x76y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_10_x76y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,889 | ERROR | FAILED | USGS_1M_11_x24y440_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x24y440_CA_SierraNevada_B22.tif'
2026-10-21 23:41:19,891 | ERROR | FAILED | USGS_1M_11_x24y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x24y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,893 | ERROR | FAILED | USGS_1M_11_x24y441_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x24y441_CA_SierraNevada_B22.tif'
2026-10-21 23:41:19,896 | ERROR | FAILED | USGS_1M_11_x24y441_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x24y441_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,901 | ERROR | FAILED | USGS_1M_11_x24y442_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x24y442_CA_SierraNevada_B22.tif'
2026-10-21 23:41:19,902 | ERROR | FAILED | USGS_1M_11_x24y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x24y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,903 | ERROR | FAILED | USGS_1M_11_x24y443_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x24y443_CA_SierraNevada_B22.tif'
2026-10-21 23:41:19,904 | ERROR | FAILED | USGS_1M_11_x24y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x24y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,906 | ERROR | FAILED | USGS_1M_11_x24y444_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x24y444_CA_SierraNevada_B22.tif'
2026-10-21 23:41:19,908 | ERROR | FAILED | USGS_1M_11_x24y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x24y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,909 | ERROR | FAILED | USGS_1M_11_x24y445_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x24y445_CA_SierraNevada_B22.tif'
2026-10-21 23:41:19,911 | ERROR | FAILED | USGS_1M_11_x24y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x24y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,912 | ERROR | FAILED | USGS_1M_11_x25y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x25y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,914 | ERROR | FAILED | USGS_1M_11_x25y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x25y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,915 | ERROR | FAILED | USGS_1M_11_x25y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x25y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,917 | ERROR | FAILED | USGS_1M_11_x25y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x25y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,918 | ERROR | FAILED | USGS_1M_11_x25y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x25y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,921 | ERROR | FAILED | USGS_1M_11_x25y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x25y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,922 | ERROR | FAILED | USGS_1M_11_x26y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x26y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,924 | ERROR | FAILED | USGS_1M_11_x26y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x26y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,926 | ERROR | FAILED | USGS_1M_11_x26y449_NV_Humboldt_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_Humboldt_2021_D21/USGS_1M_11_x26y449_NV_Humboldt_2021_D21.tif'
2026-10-21 23:41:19,928 | ERROR | FAILED | USGS_1M_11_x26y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x26y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,930 | ERROR | FAILED | USGS_1M_11_x27y435_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x27y435_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,932 | ERROR | FAILED | USGS_1M_11_x27y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x27y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,933 | ERROR | FAILED | USGS_1M_11_x27y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x27y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,935 | ERROR | FAILED | USGS_1M_11_x27y441_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x27y441_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,936 | ERROR | FAILED | USGS_1M_11_x27y449_NV_Humboldt_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_Humboldt_2021_D21/USGS_1M_11_x27y449_NV_Humboldt_2021_D21.tif'
2026-10-21 23:41:19,938 | ERROR | FAILED | USGS_1M_11_x27y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x27y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,940 | ERROR | FAILED | USGS_1M_11_x27y450_NV_Humboldt_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_Humboldt_2021_D21/USGS_1M_11_x27y450_NV_Humboldt_2021_D21.tif'
2026-10-21 23:41:19,942 | ERROR | FAILED | USGS_1M_11_x27y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x27y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,945 | ERROR | FAILED | USGS_1M_11_x28y433_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x28y433_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,946 | ERROR | FAILED | USGS_1M_11_x28y434_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x28y434_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,949 | ERROR | FAILED | USGS_1M_11_x28y435_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x28y435_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,951 | ERROR | FAILED | USGS_1M_11_x28y436_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x28y436_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,952 | ERROR | FAILED | USGS_1M_11_x28y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x28y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,954 | ERROR | FAILED | USGS_1M_11_x28y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x28y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,958 | ERROR | FAILED | USGS_1M_11_x28y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x28y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,960 | ERROR | FAILED | USGS_1M_11_x28y450_NV_Humboldt_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_Humboldt_2021_D21/USGS_1M_11_x28y450_NV_Humboldt_2021_D21.tif'
2026-10-21 23:41:19,963 | ERROR | FAILED | USGS_1M_11_x28y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x28y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,965 | ERROR | FAILED | USGS_1M_11_x28y451_NV_Humboldt_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_Humboldt_2021_D21/USGS_1M_11_x28y451_NV_Humboldt_2021_D21.tif'
2026-10-21 23:41:19,968 | ERROR | FAILED | USGS_1M_11_x29y431_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x29y431_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,970 | ERROR | FAILED | USGS_1M_11_x29y432_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x29y432_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,972 | ERROR | FAILED | USGS_1M_11_x29y433_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x29y433_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,975 | ERROR | FAILED | USGS_1M_11_x29y434_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x29y434_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,977 | ERROR | FAILED | USGS_1M_11_x29y435_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x29y435_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,979 | ERROR | FAILED | USGS_1M_11_x29y436_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x29y436_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,981 | ERROR | FAILED | USGS_1M_11_x29y437_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x29y437_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,984 | ERROR | FAILED | USGS_1M_11_x29y438_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x29y438_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,986 | ERROR | FAILED | USGS_1M_11_x29y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x29y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,989 | ERROR | FAILED | USGS_1M_11_x29y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x29y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,993 | ERROR | FAILED | USGS_1M_11_x29y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x29y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:19,995 | ERROR | FAILED | USGS_1M_11_x29y450_NV_Humboldt_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_Humboldt_2021_D21/USGS_1M_11_x29y450_NV_Humboldt_2021_D21.tif'
2026-10-21 23:41:19,997 | ERROR | FAILED | USGS_1M_11_x29y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x29y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,001 | ERROR | FAILED | USGS_1M_11_x29y451_NV_Humboldt_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_Humboldt_2021_D21/USGS_1M_11_x29y451_NV_Humboldt_2021_D21.tif'
2026-10-21 23:41:20,002 | ERROR | FAILED | USGS_1M_11_x30y430_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x30y430_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,003 | ERROR | FAILED | USGS_1M_11_x30y431_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x30y431_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,007 | ERROR | FAILED | USGS_1M_11_x30y432_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x30y432_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,008 | ERROR | FAILED | USGS_1M_11_x30y433_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x30y433_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,011 | ERROR | FAILED | USGS_1M_11_x30y434_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x30y434_NV_WestCentral_EarthMRI_2020_D20.tif'

DEM 9/894: USGS_1M_10_x75y445_CA_SierraNevada_B22.tif

DEM 10/894: USGS_1M_10_x75y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 11/894: USGS_1M_10_x76y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 12/894: USGS_1M_10_x76y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 13/894: USGS_1M_10_x76y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 14/894: USGS_1M_10_x76y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 15/894: USGS_1M_10_x76y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 16/894: USGS_1M_10_x76y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 17/894: USGS_1M_11_x24y440_CA_SierraNevada_B22.tif

DEM 18/894: USGS_1M_11_x24y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 19/894: USGS_1M_11_x24y441_CA_SierraNevada_B22.tif

DEM 20/894: USGS_1M_11_x24y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 21/894: USGS_1M_11_x24y442_CA_SierraNevada_B22.tif

DEM 22/894: USGS_1M_11_x24y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 23/894: USGS_1M_11_x24y443_CA_SierraNevada_B22.tif

DEM 24/894: USGS_1M_11_x24y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 25/894: USGS_1M_11_x24y444_CA_SierraNevada_B22.tif

DEM 26/894: USGS_1M_11_x24y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 27/894: USGS_1M_11_x24y445_CA_SierraNevada_B22.tif

DEM 28/894: USGS_1M_11_x24y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 29/894: USGS_1M_11_x25y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 30/894: USGS_1M_11_x25y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 31/894: USGS_1M_11_x25y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 32/894: USGS_1M_11_x25y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 33/894: USGS_1M_11_x25y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 34/894: USGS_1M_11_x25y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 35/894: USGS_1M_11_x26y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 36/894: USGS_1M_11_x26y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 37/894: USGS_1M_11_x26y449_NV_Humboldt_2021_D21.tif

DEM 38/894: USGS_1M_11_x26y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 39/894: USGS_1M_11_x27y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 40/894: USGS_1M_11_x27y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 41/894: USGS_1M_11_x27y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 42/894: USGS_1M_11_x27y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 43/894: USGS_1M_11_x27y449_NV_Humboldt_2021_D21.tif

DEM 44/894: USGS_1M_11_x27y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 45/894: USGS_1M_11_x27y450_NV_Humboldt_2021_D21.tif

DEM 46/894: USGS_1M_11_x27y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 47/894: USGS_1M_11_x28y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 48/894: USGS_1M_11_x28y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 49/894: USGS_1M_11_x28y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 50/894: USGS_1M_11_x28y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 51/894: USGS_1M_11_x28y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 52/894: USGS_1M_11_x28y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 53/894: USGS_1M_11_x28y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 54/894: USGS_1M_11_x28y450_NV_Humboldt_2021_D21.tif

DEM 55/894: USGS_1M_11_x28y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 56/894: USGS_1M_11_x28y451_NV_Humboldt_2021_D21.tif

DEM 57/894: USGS_1M_11_x29y431_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 58/894: USGS_1M_11_x29y432_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 59/894: USGS_1M_11_x29y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 60/894: USGS_1M_11_x29y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 61/894: USGS_1M_11_x29y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 62/894: USGS_1M_11_x29y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 63/894: USGS_1M_11_x29y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 64/894: USGS_1M_11_x29y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 65/894: USGS_1M_11_x29y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 66/894: USGS_1M_11_x29y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 67/894: USGS_1M_11_x29y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 68/894: USGS_1M_11_x29y450_NV_Humboldt_2021_D21.tif

DEM 69/894: USGS_1M_11_x29y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 70/894: USGS_1M_11_x29y451_NV_Humboldt_2021_D21.tif

DEM 71/894: USGS_1M_11_x30y430_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 72/894: USGS_1M_11_x30y431_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 73/894: USGS_1M_11_x30y432_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 74/894: USGS_1M_11_x30y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 75/894: USGS_1M_11_x30y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 76/894: USGS_1M_11_x30y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 77/894: USGS_1M_11_x30y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 78/894: USGS_1M_11_x30y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 79/894: USGS_1M_11_x30y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 80/894: USGS_1M_11_x30y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 81/894: USGS_1M_11_x30y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 82/894: USGS_1M_11_x30y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 83/894: USGS_1M_11_x30y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 84/894: USGS_1M_11_x30y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 85/894: USGS_1M_11_x30y450_NV_Humboldt_2021_D21.tif

DEM 86/894: USGS_1M_11_x30y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 87/894: USGS_1M_11_x30y451_NV_Humboldt_2021_D21.tif

DEM 88/894: USGS_1M_11_x30y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 89/894: USGS_1M_11_x31y428_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 90/894: USGS_1M_11_x31y429_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 91/894: USGS_1M_11_x31y430_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 92/894: USGS_1M_11_x31y431_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 93/894: USGS_1M_11_x31y432_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 94/894: USGS_1M_11_x31y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 95/894: USGS_1M_11_x31y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 96/894: USGS_1M_11_x31y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 97/894: USGS_1M_11_x31y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 98/894: USGS_1M_11_x31y437_NV_WestCentral_EarthMRI_2020_D20.tif

2026-10-21 23:41:20,073 | ERROR | FAILED | USGS_1M_11_x31y437_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y437_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,077 | ERROR | FAILED | USGS_1M_11_x31y438_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y438_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,082 | ERROR | FAILED | USGS_1M_11_x31y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,084 | ERROR | FAILED | USGS_1M_11_x31y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,086 | ERROR | FAILED | USGS_1M_11_x31y441_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y441_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,089 | ERROR | FAILED | USGS_1M_11_x31y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,093 | ERROR | FAILED | USGS_1M_11_x31y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,095 | ERROR | FAILED | USGS_1M_11_x31y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,098 | ERROR | FAILED | USGS_1M_11_x31y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,099 | ERROR | FAILED | USGS_1M_11_x31y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,101 | ERROR | FAILED | USGS_1M_11_x31y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,103 | ERROR | FAILED | USGS_1M_11_x31y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,105 | ERROR | FAILED | USGS_1M_11_x31y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,109 | ERROR | FAILED | USGS_1M_11_x31y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,112 | ERROR | FAILED | USGS_1M_11_x31y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x31y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,114 | ERROR | FAILED | USGS_1M_11_x32y426_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y426_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,116 | ERROR | FAILED | USGS_1M_11_x32y427_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y427_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,120 | ERROR | FAILED | USGS_1M_11_x32y428_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y428_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,121 | ERROR | FAILED | USGS_1M_11_x32y429_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y429_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,125 | ERROR | FAILED | USGS_1M_11_x32y430_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y430_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,126 | ERROR | FAILED | USGS_1M_11_x32y431_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y431_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,129 | ERROR | FAILED | USGS_1M_11_x32y432_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y432_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,130 | ERROR | FAILED | USGS_1M_11_x32y433_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y433_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,131 | ERROR | FAILED | USGS_1M_11_x32y434_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y434_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,135 | ERROR | FAILED | USGS_1M_11_x32y435_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y435_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,136 | ERROR | FAILED | USGS_1M_11_x32y436_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y436_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,138 | ERROR | FAILED | USGS_1M_11_x32y437_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y437_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,142 | ERROR | FAILED | USGS_1M_11_x32y438_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y438_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,146 | ERROR | FAILED | USGS_1M_11_x32y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,147 | ERROR | FAILED | USGS_1M_11_x32y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,150 | ERROR | FAILED | USGS_1M_11_x32y441_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y441_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,154 | ERROR | FAILED | USGS_1M_11_x32y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,156 | ERROR | FAILED | USGS_1M_11_x32y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,160 | ERROR | FAILED | USGS_1M_11_x32y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,162 | ERROR | FAILED | USGS_1M_11_x32y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,164 | ERROR | FAILED | USGS_1M_11_x32y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,167 | ERROR | FAILED | USGS_1M_11_x32y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,168 | ERROR | FAILED | USGS_1M_11_x32y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,172 | ERROR | FAILED | USGS_1M_11_x32y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,174 | ERROR | FAILED | USGS_1M_11_x32y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,176 | ERROR | FAILED | USGS_1M_11_x32y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x32y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,179 | ERROR | FAILED | USGS_1M_11_x33y424_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x33y424_CA_SierraNevada_B22.tif'
2026-10-21 23:41:20,182 | ERROR | FAILED | USGS_1M_11_x33y424_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y424_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,185 | ERROR | FAILED | USGS_1M_11_x33y425_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y425_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,186 | ERROR | FAILED | USGS_1M_11_x33y426_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y426_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,188 | ERROR | FAILED | USGS_1M_11_x33y427_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y427_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,190 | ERROR | FAILED | USGS_1M_11_x33y428_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y428_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,193 | ERROR | FAILED | USGS_1M_11_x33y429_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y429_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,194 | ERROR | FAILED | USGS_1M_11_x33y430_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y430_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,196 | ERROR | FAILED | USGS_1M_11_x33y431_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y431_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,199 | ERROR | FAILED | USGS_1M_11_x33y432_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y432_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,200 | ERROR | FAILED | USGS_1M_11_x33y433_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y433_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,205 | ERROR | FAILED | USGS_1M_11_x33y434_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y434_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,208 | ERROR | FAILED | USGS_1M_11_x33y435_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y435_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,211 | ERROR | FAILED | USGS_1M_11_x33y436_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y436_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,216 | ERROR | FAILED | USGS_1M_11_x33y437_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y437_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,222 | ERROR | FAILED | USGS_1M_11_x33y438_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y438_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,226 | ERROR | FAILED | USGS_1M_11_x33y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,229 | ERROR | FAILED | USGS_1M_11_x33y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,236 | ERROR | FAILED | USGS_1M_11_x33y441_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y441_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,238 | ERROR | FAILED | USGS_1M_11_x33y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,243 | ERROR | FAILED | USGS_1M_11_x33y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,248 | ERROR | FAILED | USGS_1M_11_x33y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,254 | ERROR | FAILED | USGS_1M_11_x33y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,257 | ERROR | FAILED | USGS_1M_11_x33y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,260 | ERROR | FAILED | USGS_1M_11_x33y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,263 | ERROR | FAILED | USGS_1M_11_x33y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,271 | ERROR | FAILED | USGS_1M_11_x33y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,273 | ERROR | FAILED | USGS_1M_11_x33y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x33y450_NV_WestCentral_EarthMRI_2020_D20.tif'

DEM 99/894: USGS_1M_11_x31y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 100/894: USGS_1M_11_x31y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 101/894: USGS_1M_11_x31y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 102/894: USGS_1M_11_x31y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 103/894: USGS_1M_11_x31y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 104/894: USGS_1M_11_x31y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 105/894: USGS_1M_11_x31y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 106/894: USGS_1M_11_x31y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 107/894: USGS_1M_11_x31y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 108/894: USGS_1M_11_x31y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 109/894: USGS_1M_11_x31y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 110/894: USGS_1M_11_x31y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 111/894: USGS_1M_11_x31y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 112/894: USGS_1M_11_x31y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 113/894: USGS_1M_11_x32y426_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 114/894: USGS_1M_11_x32y427_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 115/894: USGS_1M_11_x32y428_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 116/894: USGS_1M_11_x32y429_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 117/894: USGS_1M_11_x32y430_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 118/894: USGS_1M_11_x32y431_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 119/894: USGS_1M_11_x32y432_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 120/894: USGS_1M_11_x32y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 121/894: USGS_1M_11_x32y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 122/894: USGS_1M_11_x32y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 123/894: USGS_1M_11_x32y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 124/894: USGS_1M_11_x32y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 125/894: USGS_1M_11_x32y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 126/894: USGS_1M_11_x32y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 127/894: USGS_1M_11_x32y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 128/894: USGS_1M_11_x32y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 129/894: USGS_1M_11_x32y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 130/894: USGS_1M_11_x32y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 131/894: USGS_1M_11_x32y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 132/894: USGS_1M_11_x32y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 133/894: USGS_1M_11_x32y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 134/894: USGS_1M_11_x32y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 135/894: USGS_1M_11_x32y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 136/894: USGS_1M_11_x32y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 137/894: USGS_1M_11_x32y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 138/894: USGS_1M_11_x32y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 139/894: USGS_1M_11_x33y424_CA_SierraNevada_B22.tif

DEM 140/894: USGS_1M_11_x33y424_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 141/894: USGS_1M_11_x33y425_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 142/894: USGS_1M_11_x33y426_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 143/894: USGS_1M_11_x33y427_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 144/894: USGS_1M_11_x33y428_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 145/894: USGS_1M_11_x33y429_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 146/894: USGS_1M_11_x33y430_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 147/894: USGS_1M_11_x33y431_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 148/894: USGS_1M_11_x33y432_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 149/894: USGS_1M_11_x33y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 150/894: USGS_1M_11_x33y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 151/894: USGS_1M_11_x33y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 152/894: USGS_1M_11_x33y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 153/894: USGS_1M_11_x33y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 154/894: USGS_1M_11_x33y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 155/894: USGS_1M_11_x33y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 156/894: USGS_1M_11_x33y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 157/894: USGS_1M_11_x33y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 158/894: USGS_1M_11_x33y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 159/894: USGS_1M_11_x33y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 160/894: USGS_1M_11_x33y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 161/894: USGS_1M_11_x33y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 162/894: USGS_1M_11_x33y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 163/894: USGS_1M_11_x33y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 164/894: USGS_1M_11_x33y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 165/894: USGS_1M_11_x33y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 166/894: USGS_1M_11_x33y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 167/894: USGS_1M_11_x33y451_NV_WestCentral_EarthMRI_2020_D20.tif

2026-10-21 23:41:20,289 | ERROR | FAILED | USGS_1M_11_x34y423_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x34y423_CA_SierraNevada_B22.tif'
2026-10-21 23:41:20,297 | ERROR | FAILED | USGS_1M_11_x34y423_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y423_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,300 | ERROR | FAILED | USGS_1M_11_x34y424_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y424_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,306 | ERROR | FAILED | USGS_1M_11_x34y425_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y425_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,308 | ERROR | FAILED | USGS_1M_11_x34y426_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y426_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,312 | ERROR | FAILED | USGS_1M_11_x34y427_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y427_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,315 | ERROR | FAILED | USGS_1M_11_x34y428_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y428_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,320 | ERROR | FAILED | USGS_1M_11_x34y429_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y429_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,326 | ERROR | FAILED | USGS_1M_11_x34y430_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y430_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,329 | ERROR | FAILED | USGS_1M_11_x34y431_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y431_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,333 | ERROR | FAILED | USGS_1M_11_x34y432_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y432_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,337 | ERROR | FAILED | USGS_1M_11_x34y433_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y433_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,343 | ERROR | FAILED | USGS_1M_11_x34y434_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y434_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,345 | ERROR | FAILED | USGS_1M_11_x34y435_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y435_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,347 | ERROR | FAILED | USGS_1M_11_x34y436_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y436_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,353 | ERROR | FAILED | USGS_1M_11_x34y437_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y437_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,354 | ERROR | FAILED | USGS_1M_11_x34y438_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y438_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,357 | ERROR | FAILED | USGS_1M_11_x34y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,362 | ERROR | FAILED | USGS_1M_11_x34y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,365 | ERROR | FAILED | USGS_1M_11_x34y441_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y441_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,368 | ERROR | FAILED | USGS_1M_11_x34y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,371 | ERROR | FAILED | USGS_1M_11_x34y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,372 | ERROR | FAILED | USGS_1M_11_x34y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,375 | ERROR | FAILED | USGS_1M_11_x34y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,378 | ERROR | FAILED | USGS_1M_11_x34y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,381 | ERROR | FAILED | USGS_1M_11_x34y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,384 | ERROR | FAILED | USGS_1M_11_x34y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,385 | ERROR | FAILED | USGS_1M_11_x34y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,387 | ERROR | FAILED | USGS_1M_11_x34y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,389 | ERROR | FAILED | USGS_1M_11_x34y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x34y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,391 | ERROR | FAILED | USGS_1M_11_x35y421_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x35y421_CA_SierraNevada_B22.tif'
2026-10-21 23:41:20,394 | ERROR | FAILED | USGS_1M_11_x35y421_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y421_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,396 | ERROR | FAILED | USGS_1M_11_x35y422_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x35y422_CA_SierraNevada_B22.tif'
2026-10-21 23:41:20,403 | ERROR | FAILED | USGS_1M_11_x35y422_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y422_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,407 | ERROR | FAILED | USGS_1M_11_x35y423_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y423_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,409 | ERROR | FAILED | USGS_1M_11_x35y424_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y424_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,411 | ERROR | FAILED | USGS_1M_11_x35y425_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y425_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,415 | ERROR | FAILED | USGS_1M_11_x35y426_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y426_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,417 | ERROR | FAILED | USGS_1M_11_x35y427_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y427_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,419 | ERROR | FAILED | USGS_1M_11_x35y428_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y428_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,423 | ERROR | FAILED | USGS_1M_11_x35y429_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y429_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,424 | ERROR | FAILED | USGS_1M_11_x35y430_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y430_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,425 | ERROR | FAILED | USGS_1M_11_x35y431_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y431_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,427 | ERROR | FAILED | USGS_1M_11_x35y432_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y432_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,434 | ERROR | FAILED | USGS_1M_11_x35y433_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y433_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,443 | ERROR | FAILED | USGS_1M_11_x35y434_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y434_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,446 | ERROR | FAILED | USGS_1M_11_x35y435_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y435_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,452 | ERROR | FAILED | USGS_1M_11_x35y436_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y436_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,454 | ERROR | FAILED | USGS_1M_11_x35y437_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y437_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,458 | ERROR | FAILED | USGS_1M_11_x35y438_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y438_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,459 | ERROR | FAILED | USGS_1M_11_x35y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,463 | ERROR | FAILED | USGS_1M_11_x35y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,465 | ERROR | FAILED | USGS_1M_11_x35y441_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y441_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,469 | ERROR | FAILED | USGS_1M_11_x35y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,475 | ERROR | FAILED | USGS_1M_11_x35y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,480 | ERROR | FAILED | USGS_1M_11_x35y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,483 | ERROR | FAILED | USGS_1M_11_x35y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,485 | ERROR | FAILED | USGS_1M_11_x35y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,489 | ERROR | FAILED | USGS_1M_11_x35y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,492 | ERROR | FAILED | USGS_1M_11_x35y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y448_NV_WestCentral_EarthMRI_2020_D20.tif'

DEM 168/894: USGS_1M_11_x34y423_CA_SierraNevada_B22.tif

DEM 169/894: USGS_1M_11_x34y423_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 170/894: USGS_1M_11_x34y424_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 171/894: USGS_1M_11_x34y425_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 172/894: USGS_1M_11_x34y426_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 173/894: USGS_1M_11_x34y427_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 174/894: USGS_1M_11_x34y428_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 175/894: USGS_1M_11_x34y429_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 176/894: USGS_1M_11_x34y430_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 177/894: USGS_1M_11_x34y431_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 178/894: USGS_1M_11_x34y432_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 179/894: USGS_1M_11_x34y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 180/894: USGS_1M_11_x34y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 181/894: USGS_1M_11_x34y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 182/894: USGS_1M_11_x34y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 183/894: USGS_1M_11_x34y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 184/894: USGS_1M_11_x34y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 185/894: USGS_1M_11_x34y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 186/894: USGS_1M_11_x34y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 187/894: USGS_1M_11_x34y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 188/894: USGS_1M_11_x34y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 189/894: USGS_1M_11_x34y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 190/894: USGS_1M_11_x34y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 191/894: USGS_1M_11_x34y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 192/894: USGS_1M_11_x34y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 193/894: USGS_1M_11_x34y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 194/894: USGS_1M_11_x34y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 195/894: USGS_1M_11_x34y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 196/894: USGS_1M_11_x34y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 197/894: USGS_1M_11_x34y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 198/894: USGS_1M_11_x35y421_CA_SierraNevada_B22.tif

DEM 199/894: USGS_1M_11_x35y421_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 200/894: USGS_1M_11_x35y422_CA_SierraNevada_B22.tif

DEM 201/894: USGS_1M_11_x35y422_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 202/894: USGS_1M_11_x35y423_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 203/894: USGS_1M_11_x35y424_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 204/894: USGS_1M_11_x35y425_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 205/894: USGS_1M_11_x35y426_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 206/894: USGS_1M_11_x35y427_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 207/894: USGS_1M_11_x35y428_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 208/894: USGS_1M_11_x35y429_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 209/894: USGS_1M_11_x35y430_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 210/894: USGS_1M_11_x35y431_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 211/894: USGS_1M_11_x35y432_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 212/894: USGS_1M_11_x35y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 213/894: USGS_1M_11_x35y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 214/894: USGS_1M_11_x35y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 215/894: USGS_1M_11_x35y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 216/894: USGS_1M_11_x35y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 217/894: USGS_1M_11_x35y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 218/894: USGS_1M_11_x35y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 219/894: USGS_1M_11_x35y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 220/894: USGS_1M_11_x35y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 221/894: USGS_1M_11_x35y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 222/894: USGS_1M_11_x35y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 223/894: USGS_1M_11_x35y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 224/894: USGS_1M_11_x35y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 225/894: USGS_1M_11_x35y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 226/894: USGS_1M_11_x35y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 227/894: USGS_1M_11_x35y448_NV_WestCentral_EarthMRI_2020_D20.tif

2026-10-21 23:41:20,495 | ERROR | FAILED | USGS_1M_11_x35y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,501 | ERROR | FAILED | USGS_1M_11_x35y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,504 | ERROR | FAILED | USGS_1M_11_x35y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x35y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,508 | ERROR | FAILED | USGS_1M_11_x36y420_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x36y420_CA_SierraNevada_B22.tif'
2026-10-21 23:41:20,511 | ERROR | FAILED | USGS_1M_11_x36y420_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y420_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,517 | ERROR | FAILED | USGS_1M_11_x36y421_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x36y421_CA_SierraNevada_B22.tif'
2026-10-21 23:41:20,519 | ERROR | FAILED | USGS_1M_11_x36y421_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y421_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,521 | ERROR | FAILED | USGS_1M_11_x36y422_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y422_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,525 | ERROR | FAILED | USGS_1M_11_x36y423_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y423_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,527 | ERROR | FAILED | USGS_1M_11_x36y424_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y424_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,529 | ERROR | FAILED | USGS_1M_11_x36y425_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y425_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,532 | ERROR | FAILED | USGS_1M_11_x36y426_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y426_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,534 | ERROR | FAILED | USGS_1M_11_x36y427_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y427_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,536 | ERROR | FAILED | USGS_1M_11_x36y428_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y428_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,540 | ERROR | FAILED | USGS_1M_11_x36y429_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y429_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,541 | ERROR | FAILED | USGS_1M_11_x36y430_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y430_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,544 | ERROR | FAILED | USGS_1M_11_x36y431_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y431_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,547 | ERROR | FAILED | USGS_1M_11_x36y432_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y432_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,550 | ERROR | FAILED | USGS_1M_11_x36y433_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y433_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,552 | ERROR | FAILED | USGS_1M_11_x36y434_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y434_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,555 | ERROR | FAILED | USGS_1M_11_x36y435_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y435_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,558 | ERROR | FAILED | USGS_1M_11_x36y436_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y436_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,562 | ERROR | FAILED | USGS_1M_11_x36y437_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y437_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,564 | ERROR | FAILED | USGS_1M_11_x36y438_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y438_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,567 | ERROR | FAILED | USGS_1M_11_x36y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,570 | ERROR | FAILED | USGS_1M_11_x36y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,573 | ERROR | FAILED | USGS_1M_11_x36y441_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y441_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,576 | ERROR | FAILED | USGS_1M_11_x36y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,579 | ERROR | FAILED | USGS_1M_11_x36y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,580 | ERROR | FAILED | USGS_1M_11_x36y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,582 | ERROR | FAILED | USGS_1M_11_x36y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,586 | ERROR | FAILED | USGS_1M_11_x36y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,589 | ERROR | FAILED | USGS_1M_11_x36y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,590 | ERROR | FAILED | USGS_1M_11_x36y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,595 | ERROR | FAILED | USGS_1M_11_x36y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,597 | ERROR | FAILED | USGS_1M_11_x36y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,603 | ERROR | FAILED | USGS_1M_11_x36y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x36y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,611 | ERROR | FAILED | USGS_1M_11_x37y419_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x37y419_CA_SierraNevada_B22.tif'
2026-10-21 23:41:20,613 | ERROR | FAILED | USGS_1M_11_x37y419_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y419_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,616 | ERROR | FAILED | USGS_1M_11_x37y420_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x37y420_CA_SierraNevada_B22.tif'
2026-10-21 23:41:20,617 | ERROR | FAILED | USGS_1M_11_x37y420_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y420_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,619 | ERROR | FAILED | USGS_1M_11_x37y421_CA_SierraNevada_B22.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/CA_SierraNevada_B22/USGS_1M_11_x37y421_CA_SierraNevada_B22.tif'
2026-10-21 23:41:20,620 | ERROR | FAILED | USGS_1M_11_x37y421_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y421_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,622 | ERROR | FAILED | USGS_1M_11_x37y422_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y422_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,623 | ERROR | FAILED | USGS_1M_11_x37y423_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y423_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,623 | ERROR | FAILED | USGS_1M_11_x37y424_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y424_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,624 | ERROR | FAILED | USGS_1M_11_x37y425_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y425_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,626 | ERROR | FAILED | USGS_1M_11_x37y426_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y426_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,629 | ERROR | FAILED | USGS_1M_11_x37y427_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y427_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,632 | ERROR | FAILED | USGS_1M_11_x37y428_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y428_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,632 | ERROR | FAILED | USGS_1M_11_x37y429_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y429_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,633 | ERROR | FAILED | USGS_1M_11_x37y430_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y430_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,635 | ERROR | FAILED | USGS_1M_11_x37y431_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y431_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,637 | ERROR | FAILED | USGS_1M_11_x37y432_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y432_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,638 | ERROR | FAILED | USGS_1M_11_x37y433_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y433_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,639 | ERROR | FAILED | USGS_1M_11_x37y434_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y434_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,640 | ERROR | FAILED | USGS_1M_11_x37y435_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y435_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,640 | ERROR | FAILED | USGS_1M_11_x37y436_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y436_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,642 | ERROR | FAILED | USGS_1M_11_x37y437_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y437_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,643 | ERROR | FAILED | USGS_1M_11_x37y438_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y438_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,644 | ERROR | FAILED | USGS_1M_11_x37y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,644 | ERROR | FAILED | USGS_1M_11_x37y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,645 | ERROR | FAILED | USGS_1M_11_x37y441_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y441_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,646 | ERROR | FAILED | USGS_1M_11_x37y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,647 | ERROR | FAILED | USGS_1M_11_x37y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,648 | ERROR | FAILED | USGS_1M_11_x37y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,650 | ERROR | FAILED | USGS_1M_11_x37y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,653 | ERROR | FAILED | USGS_1M_11_x37y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,655 | ERROR | FAILED | USGS_1M_11_x37y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,656 | ERROR | FAILED | USGS_1M_11_x37y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x37y448_NV_WestCentral_EarthMRI_2020_D20.tif'

DEM 228/894: USGS_1M_11_x35y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 229/894: USGS_1M_11_x35y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 230/894: USGS_1M_11_x35y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 231/894: USGS_1M_11_x36y420_CA_SierraNevada_B22.tif

DEM 232/894: USGS_1M_11_x36y420_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 233/894: USGS_1M_11_x36y421_CA_SierraNevada_B22.tif

DEM 234/894: USGS_1M_11_x36y421_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 235/894: USGS_1M_11_x36y422_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 236/894: USGS_1M_11_x36y423_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 237/894: USGS_1M_11_x36y424_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 238/894: USGS_1M_11_x36y425_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 239/894: USGS_1M_11_x36y426_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 240/894: USGS_1M_11_x36y427_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 241/894: USGS_1M_11_x36y428_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 242/894: USGS_1M_11_x36y429_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 243/894: USGS_1M_11_x36y430_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 244/894: USGS_1M_11_x36y431_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 245/894: USGS_1M_11_x36y432_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 246/894: USGS_1M_11_x36y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 247/894: USGS_1M_11_x36y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 248/894: USGS_1M_11_x36y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 249/894: USGS_1M_11_x36y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 250/894: USGS_1M_11_x36y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 251/894: USGS_1M_11_x36y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 252/894: USGS_1M_11_x36y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 253/894: USGS_1M_11_x36y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 254/894: USGS_1M_11_x36y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 255/894: USGS_1M_11_x36y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 256/894: USGS_1M_11_x36y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 257/894: USGS_1M_11_x36y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 258/894: USGS_1M_11_x36y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 259/894: USGS_1M_11_x36y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 260/894: USGS_1M_11_x36y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 261/894: USGS_1M_11_x36y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 262/894: USGS_1M_11_x36y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 263/894: USGS_1M_11_x36y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 264/894: USGS_1M_11_x36y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 265/894: USGS_1M_11_x37y419_CA_SierraNevada_B22.tif

DEM 266/894: USGS_1M_11_x37y419_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 267/894: USGS_1M_11_x37y420_CA_SierraNevada_B22.tif

DEM 268/894: USGS_1M_11_x37y420_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 269/894: USGS_1M_11_x37y421_CA_SierraNevada_B22.tif

DEM 270/894: USGS_1M_11_x37y421_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 271/894: USGS_1M_11_x37y422_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 272/894: USGS_1M_11_x37y423_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 273/894: USGS_1M_11_x37y424_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 274/894: USGS_1M_11_x37y425_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 275/894: USGS_1M_11_x37y426_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 276/894: USGS_1M_11_x37y427_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 277/894: USGS_1M_11_x37y428_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 278/894: USGS_1M_11_x37y429_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 279/894: USGS_1M_11_x37y430_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 280/894: USGS_1M_11_x37y431_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 281/894: USGS_1M_11_x37y432_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 282/894: USGS_1M_11_x37y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 283/894: USGS_1M_11_x37y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 284/894: USGS_1M_11_x37y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 285/894: USGS_1M_11_x37y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 286/894: USGS_1M_11_x37y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 287/894: USGS_1M_11_x37y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 288/894: USGS_1M_11_x37y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 289/894: USGS_1M_11_x37y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 290/894: USGS_1M_11_x37y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 291/894: USGS_1M_11_x37y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 292/894: USGS_1M_11_x37y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 293/894: USGS_1M_11_x37y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 294/894: USGS_1M_11_x37y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 295/894: USGS_1M_11_x37y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 296/894: USGS_1M_11_x37y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 297/894: USGS_1M_11_x37y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 298/894: USGS_1M_11_x37y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 299/894: USGS_1M_11_x37y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 300/894: USGS_1M_11_x37y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 301/894: USGS_1M_11_x38y418_CA_SierraNevada_B22.tif

DEM 302/894: USGS_1M_11_x38y419_CA_SierraNevada_B22.tif

DEM 303/894: USGS_1M_11_x38y419_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 304/894: USGS_1M_11_x38y420_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 305/894: USGS_1M_11_x38y421_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 306/894: USGS_1M_11_x38y422_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 307/894: USGS_1M_11_x38y423_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 308/894: USGS_1M_11_x38y424_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 309/894: USGS_1M_11_x38y425_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 310/894: USGS_1M_11_x38y426_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 311/894: USGS_1M_11_x38y427_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 312/894: USGS_1M_11_x38y428_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 313/894: USGS_1M_11_x38y429_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 314/894: USGS_1M_11_x38y430_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 315/894: USGS_1M_11_x38y431_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 316/894: USGS_1M_11_x38y432_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 317/894: USGS_1M_11_x38y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 318/894: USGS_1M_11_x38y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 319/894: USGS_1M_11_x38y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 320/894: USGS_1M_11_x38y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 321/894: USGS_1M_11_x38y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 322/894: USGS_1M_11_x38y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 323/894: USGS_1M_11_x38y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 324/894: USGS_1M_11_x38y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 325/894: USGS_1M_11_x38y441_NV_WestCentral_EarthMRI_2020_D20.tif

2026-10-21 23:41:20,697 | ERROR | FAILED | USGS_1M_11_x38y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x38y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,698 | ERROR | FAILED | USGS_1M_11_x38y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x38y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,698 | ERROR | FAILED | USGS_1M_11_x38y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x38y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,701 | ERROR | FAILED | USGS_1M_11_x38y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x38y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,702 | ERROR | FAILED | USGS_1M_11_x38y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x38y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,705 | ERROR | FAILED | USGS_1M_11_x38y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x38y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,707 | ERROR | FAILED | USGS_1M_11_x38y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x38y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,708 | ERROR | FAILED | USGS_1M_11_x38y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x38y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,709 | ERROR | FAILED | USGS_1M_11_x38y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x38y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,711 | ERROR | FAILED | USGS_1M_11_x38y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x38y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,712 | ERROR | FAILED | USGS_1M_11_x39y417_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y417_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,713 | ERROR | FAILED | USGS_1M_11_x39y418_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y418_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,715 | ERROR | FAILED | USGS_1M_11_x39y419_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y419_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,727 | ERROR | FAILED | USGS_1M_11_x39y420_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y420_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,733 | ERROR | FAILED | USGS_1M_11_x39y421_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y421_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,744 | ERROR | FAILED | USGS_1M_11_x39y422_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y422_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,746 | ERROR | FAILED | USGS_1M_11_x39y423_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y423_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,751 | ERROR | FAILED | USGS_1M_11_x39y424_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y424_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,758 | ERROR | FAILED | USGS_1M_11_x39y425_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y425_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,761 | ERROR | FAILED | USGS_1M_11_x39y426_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y426_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,764 | ERROR | FAILED | USGS_1M_11_x39y427_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y427_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,767 | ERROR | FAILED | USGS_1M_11_x39y428_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y428_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,770 | ERROR | FAILED | USGS_1M_11_x39y429_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y429_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,772 | ERROR | FAILED | USGS_1M_11_x39y430_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y430_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,776 | ERROR | FAILED | USGS_1M_11_x39y431_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y431_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,778 | ERROR | FAILED | USGS_1M_11_x39y432_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y432_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,781 | ERROR | FAILED | USGS_1M_11_x39y433_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y433_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,782 | ERROR | FAILED | USGS_1M_11_x39y434_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y434_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,784 | ERROR | FAILED | USGS_1M_11_x39y435_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y435_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,786 | ERROR | FAILED | USGS_1M_11_x39y436_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y436_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,788 | ERROR | FAILED | USGS_1M_11_x39y437_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y437_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,791 | ERROR | FAILED | USGS_1M_11_x39y438_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y438_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,793 | ERROR | FAILED | USGS_1M_11_x39y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,794 | ERROR | FAILED | USGS_1M_11_x39y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,795 | ERROR | FAILED | USGS_1M_11_x39y441_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y441_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,796 | ERROR | FAILED | USGS_1M_11_x39y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,797 | ERROR | FAILED | USGS_1M_11_x39y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,798 | ERROR | FAILED | USGS_1M_11_x39y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,799 | ERROR | FAILED | USGS_1M_11_x39y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,800 | ERROR | FAILED | USGS_1M_11_x39y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,801 | ERROR | FAILED | USGS_1M_11_x39y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,802 | ERROR | FAILED | USGS_1M_11_x39y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,803 | ERROR | FAILED | USGS_1M_11_x39y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,804 | ERROR | FAILED | USGS_1M_11_x39y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,805 | ERROR | FAILED | USGS_1M_11_x39y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x39y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,806 | ERROR | FAILED | USGS_1M_11_x40y416_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y416_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,807 | ERROR | FAILED | USGS_1M_11_x40y417_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y417_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,808 | ERROR | FAILED | USGS_1M_11_x40y418_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y418_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,808 | ERROR | FAILED | USGS_1M_11_x40y419_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y419_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,809 | ERROR | FAILED | USGS_1M_11_x40y420_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y420_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,810 | ERROR | FAILED | USGS_1M_11_x40y421_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y421_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,811 | ERROR | FAILED | USGS_1M_11_x40y422_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y422_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,812 | ERROR | FAILED | USGS_1M_11_x40y423_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y423_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,813 | ERROR | FAILED | USGS_1M_11_x40y424_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y424_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,814 | ERROR | FAILED | USGS_1M_11_x40y425_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y425_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,814 | ERROR | FAILED | USGS_1M_11_x40y426_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y426_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,815 | ERROR | FAILED | USGS_1M_11_x40y427_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y427_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,816 | ERROR | FAILED | USGS_1M_11_x40y428_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y428_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,817 | ERROR | FAILED | USGS_1M_11_x40y429_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y429_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,818 | ERROR | FAILED | USGS_1M_11_x40y430_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y430_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,819 | ERROR | FAILED | USGS_1M_11_x40y431_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y431_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,820 | ERROR | FAILED | USGS_1M_11_x40y432_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y432_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,820 | ERROR | FAILED | USGS_1M_11_x40y433_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y433_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,821 | ERROR | FAILED | USGS_1M_11_x40y434_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y434_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,822 | ERROR | FAILED | USGS_1M_11_x40y435_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y435_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,823 | ERROR | FAILED | USGS_1M_11_x40y436_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y436_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,824 | ERROR | FAILED | USGS_1M_11_x40y437_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y437_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,825 | ERROR | FAILED | USGS_1M_11_x40y438_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y438_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,828 | ERROR | FAILED | USGS_1M_11_x40y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x40y439_NV_WestCentral_EarthMRI_2020_D20.tif'

DEM 326/894: USGS_1M_11_x38y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 327/894: USGS_1M_11_x38y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 328/894: USGS_1M_11_x38y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 329/894: USGS_1M_11_x38y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 330/894: USGS_1M_11_x38y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 331/894: USGS_1M_11_x38y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 332/894: USGS_1M_11_x38y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 333/894: USGS_1M_11_x38y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 334/894: USGS_1M_11_x38y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 335/894: USGS_1M_11_x38y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 336/894: USGS_1M_11_x39y417_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 337/894: USGS_1M_11_x39y418_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 338/894: USGS_1M_11_x39y419_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 339/894: USGS_1M_11_x39y420_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 340/894: USGS_1M_11_x39y421_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 341/894: USGS_1M_11_x39y422_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 342/894: USGS_1M_11_x39y423_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 343/894: USGS_1M_11_x39y424_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 344/894: USGS_1M_11_x39y425_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 345/894: USGS_1M_11_x39y426_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 346/894: USGS_1M_11_x39y427_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 347/894: USGS_1M_11_x39y428_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 348/894: USGS_1M_11_x39y429_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 349/894: USGS_1M_11_x39y430_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 350/894: USGS_1M_11_x39y431_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 351/894: USGS_1M_11_x39y432_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 352/894: USGS_1M_11_x39y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 353/894: USGS_1M_11_x39y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 354/894: USGS_1M_11_x39y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 355/894: USGS_1M_11_x39y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 356/894: USGS_1M_11_x39y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 357/894: USGS_1M_11_x39y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 358/894: USGS_1M_11_x39y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 359/894: USGS_1M_11_x39y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 360/894: USGS_1M_11_x39y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 361/894: USGS_1M_11_x39y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 362/894: USGS_1M_11_x39y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 363/894: USGS_1M_11_x39y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 364/894: USGS_1M_11_x39y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 365/894: USGS_1M_11_x39y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 366/894: USGS_1M_11_x39y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 367/894: USGS_1M_11_x39y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 368/894: USGS_1M_11_x39y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 369/894: USGS_1M_11_x39y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 370/894: USGS_1M_11_x39y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 371/894: USGS_1M_11_x40y416_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 372/894: USGS_1M_11_x40y417_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 373/894: USGS_1M_11_x40y418_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 374/894: USGS_1M_11_x40y419_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 375/894: USGS_1M_11_x40y420_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 376/894: USGS_1M_11_x40y421_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 377/894: USGS_1M_11_x40y422_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 378/894: USGS_1M_11_x40y423_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 379/894: USGS_1M_11_x40y424_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 380/894: USGS_1M_11_x40y425_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 381/894: USGS_1M_11_x40y426_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 382/894: USGS_1M_11_x40y427_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 383/894: USGS_1M_11_x40y428_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 384/894: USGS_1M_11_x40y429_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 385/894: USGS_1M_11_x40y430_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 386/894: USGS_1M_11_x40y431_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 387/894: USGS_1M_11_x40y432_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 388/894: USGS_1M_11_x40y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 389/894: USGS_1M_11_x40y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 390/894: USGS_1M_11_x40y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 391/894: USGS_1M_11_x40y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 392/894: USGS_1M_11_x40y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 393/894: USGS_1M_11_x40y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 394/894: USGS_1M_11_x40y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 395/894: USGS_1M_11_x40y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 396/894: USGS_1M_11_x40y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 397/894: USGS_1M_11_x40y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 398/894: USGS_1M_11_x40y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 399/894: USGS_1M_11_x40y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 400/894: USGS_1M_11_x40y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 401/894: USGS_1M_11_x40y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 402/894: USGS_1M_11_x40y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 403/894: USGS_1M_11_x40y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 404/894: USGS_1M_11_x40y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 405/894: USGS_1M_11_x40y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 406/894: USGS_1M_11_x40y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 407/894: USGS_1M_11_x41y414_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 408/894: USGS_1M_11_x41y415_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 409/894: USGS_1M_11_x41y416_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 410/894: USGS_1M_11_x41y417_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 411/894: USGS_1M_11_x41y418_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 412/894: USGS_1M_11_x41y419_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 413/894: USGS_1M_11_x41y420_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 414/894: USGS_1M_11_x41y421_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 415/894: USGS_1M_11_x41y422_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 416/894: USGS_1M_11_x41y423_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 417/894: USGS_1M_11_x41y424_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 418/894: USGS_1M_11_x41y425_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 419/894: USGS_1M_11_x41y426_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 420/894: USGS_1M_11_x41y427_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 421/894: USGS_1M_11_x41y428_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 422/894: USGS_1M_11_x41y429_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 423/894: USGS_1M_11_x41y430_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 424/894: USGS_1M_11_x41y431_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 425/894: USGS_1M_11_x41y432_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 426/894: USGS_1M_11_x41y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 427/894: USGS_1M_11_x41y434_NV_WestCentral_EarthMRI_2020_D20.tif

2026-10-21 23:41:20,899 | ERROR | FAILED | USGS_1M_11_x41y435_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y435_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,902 | ERROR | FAILED | USGS_1M_11_x41y436_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y436_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,905 | ERROR | FAILED | USGS_1M_11_x41y437_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y437_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,907 | ERROR | FAILED | USGS_1M_11_x41y438_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y438_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,909 | ERROR | FAILED | USGS_1M_11_x41y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,912 | ERROR | FAILED | USGS_1M_11_x41y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,914 | ERROR | FAILED | USGS_1M_11_x41y441_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y441_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,917 | ERROR | FAILED | USGS_1M_11_x41y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,919 | ERROR | FAILED | USGS_1M_11_x41y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,922 | ERROR | FAILED | USGS_1M_11_x41y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,927 | ERROR | FAILED | USGS_1M_11_x41y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,927 | ERROR | FAILED | USGS_1M_11_x41y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,930 | ERROR | FAILED | USGS_1M_11_x41y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,932 | ERROR | FAILED | USGS_1M_11_x41y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,935 | ERROR | FAILED | USGS_1M_11_x41y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,937 | ERROR | FAILED | USGS_1M_11_x41y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,940 | ERROR | FAILED | USGS_1M_11_x41y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x41y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,942 | ERROR | FAILED | USGS_1M_11_x42y414_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y414_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,944 | ERROR | FAILED | USGS_1M_11_x42y415_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y415_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,946 | ERROR | FAILED | USGS_1M_11_x42y416_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y416_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,949 | ERROR | FAILED | USGS_1M_11_x42y417_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y417_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,950 | ERROR | FAILED | USGS_1M_11_x42y418_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y418_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,953 | ERROR | FAILED | USGS_1M_11_x42y419_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y419_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,955 | ERROR | FAILED | USGS_1M_11_x42y420_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y420_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,957 | ERROR | FAILED | USGS_1M_11_x42y421_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y421_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,959 | ERROR | FAILED | USGS_1M_11_x42y422_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y422_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,961 | ERROR | FAILED | USGS_1M_11_x42y423_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y423_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,963 | ERROR | FAILED | USGS_1M_11_x42y424_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y424_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,965 | ERROR | FAILED | USGS_1M_11_x42y425_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y425_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,967 | ERROR | FAILED | USGS_1M_11_x42y426_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y426_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,969 | ERROR | FAILED | USGS_1M_11_x42y427_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y427_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,970 | ERROR | FAILED | USGS_1M_11_x42y428_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y428_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,972 | ERROR | FAILED | USGS_1M_11_x42y429_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y429_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,975 | ERROR | FAILED | USGS_1M_11_x42y430_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y430_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,976 | ERROR | FAILED | USGS_1M_11_x42y431_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y431_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,978 | ERROR | FAILED | USGS_1M_11_x42y432_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y432_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,979 | ERROR | FAILED | USGS_1M_11_x42y433_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y433_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,982 | ERROR | FAILED | USGS_1M_11_x42y434_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y434_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,985 | ERROR | FAILED | USGS_1M_11_x42y435_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y435_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,989 | ERROR | FAILED | USGS_1M_11_x42y436_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y436_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,990 | ERROR | FAILED | USGS_1M_11_x42y437_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y437_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,991 | ERROR | FAILED | USGS_1M_11_x42y438_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y438_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,993 | ERROR | FAILED | USGS_1M_11_x42y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,994 | ERROR | FAILED | USGS_1M_11_x42y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,997 | ERROR | FAILED | USGS_1M_11_x42y441_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y441_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:20,999 | ERROR | FAILED | USGS_1M_11_x42y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,002 | ERROR | FAILED | USGS_1M_11_x42y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,003 | ERROR | FAILED | USGS_1M_11_x42y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,005 | ERROR | FAILED | USGS_1M_11_x42y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,007 | ERROR | FAILED | USGS_1M_11_x42y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,009 | ERROR | FAILED | USGS_1M_11_x42y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,011 | ERROR | FAILED | USGS_1M_11_x42y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,014 | ERROR | FAILED | USGS_1M_11_x42y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,016 | ERROR | FAILED | USGS_1M_11_x42y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,018 | ERROR | FAILED | USGS_1M_11_x42y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x42y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,021 | ERROR | FAILED | USGS_1M_11_x43y414_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y414_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,022 | ERROR | FAILED | USGS_1M_11_x43y415_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y415_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,024 | ERROR | FAILED | USGS_1M_11_x43y416_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y416_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,026 | ERROR | FAILED | USGS_1M_11_x43y417_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y417_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,029 | ERROR | FAILED | USGS_1M_11_x43y418_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y418_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,032 | ERROR | FAILED | USGS_1M_11_x43y419_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y419_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,034 | ERROR | FAILED | USGS_1M_11_x43y420_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y420_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,036 | ERROR | FAILED | USGS_1M_11_x43y421_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y421_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,038 | ERROR | FAILED | USGS_1M_11_x43y422_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y422_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,041 | ERROR | FAILED | USGS_1M_11_x43y423_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y423_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,044 | ERROR | FAILED | USGS_1M_11_x43y424_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y424_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,048 | ERROR | FAILED | USGS_1M_11_x43y425_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y425_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,051 | ERROR | FAILED | USGS_1M_11_x43y426_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y426_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,052 | ERROR | FAILED | USGS_1M_11_x43y427_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y427_NV_WestCentral_EarthMRI_2020_D20.tif'

DEM 428/894: USGS_1M_11_x41y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 429/894: USGS_1M_11_x41y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 430/894: USGS_1M_11_x41y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 431/894: USGS_1M_11_x41y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 432/894: USGS_1M_11_x41y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 433/894: USGS_1M_11_x41y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 434/894: USGS_1M_11_x41y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 435/894: USGS_1M_11_x41y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 436/894: USGS_1M_11_x41y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 437/894: USGS_1M_11_x41y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 438/894: USGS_1M_11_x41y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 439/894: USGS_1M_11_x41y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 440/894: USGS_1M_11_x41y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 441/894: USGS_1M_11_x41y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 442/894: USGS_1M_11_x41y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 443/894: USGS_1M_11_x41y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 444/894: USGS_1M_11_x41y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 445/894: USGS_1M_11_x42y414_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 446/894: USGS_1M_11_x42y415_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 447/894: USGS_1M_11_x42y416_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 448/894: USGS_1M_11_x42y417_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 449/894: USGS_1M_11_x42y418_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 450/894: USGS_1M_11_x42y419_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 451/894: USGS_1M_11_x42y420_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 452/894: USGS_1M_11_x42y421_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 453/894: USGS_1M_11_x42y422_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 454/894: USGS_1M_11_x42y423_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 455/894: USGS_1M_11_x42y424_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 456/894: USGS_1M_11_x42y425_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 457/894: USGS_1M_11_x42y426_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 458/894: USGS_1M_11_x42y427_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 459/894: USGS_1M_11_x42y428_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 460/894: USGS_1M_11_x42y429_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 461/894: USGS_1M_11_x42y430_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 462/894: USGS_1M_11_x42y431_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 463/894: USGS_1M_11_x42y432_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 464/894: USGS_1M_11_x42y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 465/894: USGS_1M_11_x42y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 466/894: USGS_1M_11_x42y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 467/894: USGS_1M_11_x42y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 468/894: USGS_1M_11_x42y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 469/894: USGS_1M_11_x42y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 470/894: USGS_1M_11_x42y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 471/894: USGS_1M_11_x42y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 472/894: USGS_1M_11_x42y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 473/894: USGS_1M_11_x42y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 474/894: USGS_1M_11_x42y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 475/894: USGS_1M_11_x42y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 476/894: USGS_1M_11_x42y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 477/894: USGS_1M_11_x42y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 478/894: USGS_1M_11_x42y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 479/894: USGS_1M_11_x42y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 480/894: USGS_1M_11_x42y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 481/894: USGS_1M_11_x42y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 482/894: USGS_1M_11_x42y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 483/894: USGS_1M_11_x43y414_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 484/894: USGS_1M_11_x43y415_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 485/894: USGS_1M_11_x43y416_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 486/894: USGS_1M_11_x43y417_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 487/894: USGS_1M_11_x43y418_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 488/894: USGS_1M_11_x43y419_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 489/894: USGS_1M_11_x43y420_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 490/894: USGS_1M_11_x43y421_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 491/894: USGS_1M_11_x43y422_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 492/894: USGS_1M_11_x43y423_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 493/894: USGS_1M_11_x43y424_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 494/894: USGS_1M_11_x43y425_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 495/894: USGS_1M_11_x43y426_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 496/894: USGS_1M_11_x43y427_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 497/894: USGS_1M_11_x43y428_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 498/894: USGS_1M_11_x43y429_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 499/894: USGS_1M_11_x43y430_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 500/894: USGS_1M_11_x43y433_NV_EastCentral_2021_D21.tif

DEM 501/894: USGS_1M_11_x43y433_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 502/894: USGS_1M_11_x43y434_NV_EastCentral_2021_D21.tif

DEM 503/894: USGS_1M_11_x43y434_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 504/894: USGS_1M_11_x43y435_NV_EastCentral_2021_D21.tif

DEM 505/894: USGS_1M_11_x43y435_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 506/894: USGS_1M_11_x43y436_NV_EastCentral_2021_D21.tif

DEM 507/894: USGS_1M_11_x43y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 508/894: USGS_1M_11_x43y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 509/894: USGS_1M_11_x43y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 510/894: USGS_1M_11_x43y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 511/894: USGS_1M_11_x43y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 512/894: USGS_1M_11_x43y441_NV_WestCentral_EarthMRI_2020_D20.tif

2026-10-21 23:41:21,103 | ERROR | FAILED | USGS_1M_11_x43y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,106 | ERROR | FAILED | USGS_1M_11_x43y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,108 | ERROR | FAILED | USGS_1M_11_x43y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,110 | ERROR | FAILED | USGS_1M_11_x43y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,112 | ERROR | FAILED | USGS_1M_11_x43y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,119 | ERROR | FAILED | USGS_1M_11_x43y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,121 | ERROR | FAILED | USGS_1M_11_x43y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,124 | ERROR | FAILED | USGS_1M_11_x43y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,125 | ERROR | FAILED | USGS_1M_11_x43y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,126 | ERROR | FAILED | USGS_1M_11_x43y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x43y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,130 | ERROR | FAILED | USGS_1M_11_x44y414_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y414_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,135 | ERROR | FAILED | USGS_1M_11_x44y415_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y415_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,138 | ERROR | FAILED | USGS_1M_11_x44y416_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y416_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,143 | ERROR | FAILED | USGS_1M_11_x44y417_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y417_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,150 | ERROR | FAILED | USGS_1M_11_x44y418_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y418_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,154 | ERROR | FAILED | USGS_1M_11_x44y419_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y419_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,158 | ERROR | FAILED | USGS_1M_11_x44y420_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y420_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,162 | ERROR | FAILED | USGS_1M_11_x44y421_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y421_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,166 | ERROR | FAILED | USGS_1M_11_x44y422_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y422_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,168 | ERROR | FAILED | USGS_1M_11_x44y423_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y423_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,173 | ERROR | FAILED | USGS_1M_11_x44y424_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y424_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,177 | ERROR | FAILED | USGS_1M_11_x44y425_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y425_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,179 | ERROR | FAILED | USGS_1M_11_x44y426_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y426_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,182 | ERROR | FAILED | USGS_1M_11_x44y427_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y427_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,184 | ERROR | FAILED | USGS_1M_11_x44y428_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y428_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,190 | ERROR | FAILED | USGS_1M_11_x44y433_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x44y433_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,195 | ERROR | FAILED | USGS_1M_11_x44y434_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x44y434_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,198 | ERROR | FAILED | USGS_1M_11_x44y435_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x44y435_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,201 | ERROR | FAILED | USGS_1M_11_x44y436_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x44y436_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,204 | ERROR | FAILED | USGS_1M_11_x44y436_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y436_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,207 | ERROR | FAILED | USGS_1M_11_x44y437_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x44y437_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,209 | ERROR | FAILED | USGS_1M_11_x44y437_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y437_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,211 | ERROR | FAILED | USGS_1M_11_x44y438_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x44y438_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,214 | ERROR | FAILED | USGS_1M_11_x44y438_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y438_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,219 | ERROR | FAILED | USGS_1M_11_x44y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,222 | ERROR | FAILED | USGS_1M_11_x44y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,226 | ERROR | FAILED | USGS_1M_11_x44y441_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y441_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,229 | ERROR | FAILED | USGS_1M_11_x44y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,233 | ERROR | FAILED | USGS_1M_11_x44y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,240 | ERROR | FAILED | USGS_1M_11_x44y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,243 | ERROR | FAILED | USGS_1M_11_x44y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,245 | ERROR | FAILED | USGS_1M_11_x44y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,251 | ERROR | FAILED | USGS_1M_11_x44y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,256 | ERROR | FAILED | USGS_1M_11_x44y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,258 | ERROR | FAILED | USGS_1M_11_x44y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,264 | ERROR | FAILED | USGS_1M_11_x44y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,267 | ERROR | FAILED | USGS_1M_11_x44y451_NV_Humboldt_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_Humboldt_2021_D21/USGS_1M_11_x44y451_NV_Humboldt_2021_D21.tif'
2026-10-21 23:41:21,271 | ERROR | FAILED | USGS_1M_11_x44y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x44y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,275 | ERROR | FAILED | USGS_1M_11_x45y415_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y415_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,278 | ERROR | FAILED | USGS_1M_11_x45y416_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y416_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,281 | ERROR | FAILED | USGS_1M_11_x45y417_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y417_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,284 | ERROR | FAILED | USGS_1M_11_x45y418_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y418_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,287 | ERROR | FAILED | USGS_1M_11_x45y419_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y419_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,288 | ERROR | FAILED | USGS_1M_11_x45y420_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y420_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,291 | ERROR | FAILED | USGS_1M_11_x45y421_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y421_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,293 | ERROR | FAILED | USGS_1M_11_x45y422_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y422_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,296 | ERROR | FAILED | USGS_1M_11_x45y423_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y423_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,299 | ERROR | FAILED | USGS_1M_11_x45y424_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y424_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,302 | ERROR | FAILED | USGS_1M_11_x45y425_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y425_NV_WestCentral_EarthMRI_2020_D20.tif'

DEM 513/894: USGS_1M_11_x43y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 514/894: USGS_1M_11_x43y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 515/894: USGS_1M_11_x43y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 516/894: USGS_1M_11_x43y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 517/894: USGS_1M_11_x43y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 518/894: USGS_1M_11_x43y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 519/894: USGS_1M_11_x43y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 520/894: USGS_1M_11_x43y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 521/894: USGS_1M_11_x43y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 522/894: USGS_1M_11_x43y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 523/894: USGS_1M_11_x44y414_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 524/894: USGS_1M_11_x44y415_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 525/894: USGS_1M_11_x44y416_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 526/894: USGS_1M_11_x44y417_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 527/894: USGS_1M_11_x44y418_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 528/894: USGS_1M_11_x44y419_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 529/894: USGS_1M_11_x44y420_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 530/894: USGS_1M_11_x44y421_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 531/894: USGS_1M_11_x44y422_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 532/894: USGS_1M_11_x44y423_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 533/894: USGS_1M_11_x44y424_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 534/894: USGS_1M_11_x44y425_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 535/894: USGS_1M_11_x44y426_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 536/894: USGS_1M_11_x44y427_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 537/894: USGS_1M_11_x44y428_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 538/894: USGS_1M_11_x44y433_NV_EastCentral_2021_D21.tif

DEM 539/894: USGS_1M_11_x44y434_NV_EastCentral_2021_D21.tif

DEM 540/894: USGS_1M_11_x44y435_NV_EastCentral_2021_D21.tif

DEM 541/894: USGS_1M_11_x44y436_NV_EastCentral_2021_D21.tif

DEM 542/894: USGS_1M_11_x44y436_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 543/894: USGS_1M_11_x44y437_NV_EastCentral_2021_D21.tif

DEM 544/894: USGS_1M_11_x44y437_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 545/894: USGS_1M_11_x44y438_NV_EastCentral_2021_D21.tif

DEM 546/894: USGS_1M_11_x44y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 547/894: USGS_1M_11_x44y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 548/894: USGS_1M_11_x44y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 549/894: USGS_1M_11_x44y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 550/894: USGS_1M_11_x44y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 551/894: USGS_1M_11_x44y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 552/894: USGS_1M_11_x44y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 553/894: USGS_1M_11_x44y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 554/894: USGS_1M_11_x44y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 555/894: USGS_1M_11_x44y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 556/894: USGS_1M_11_x44y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 557/894: USGS_1M_11_x44y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 558/894: USGS_1M_11_x44y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 559/894: USGS_1M_11_x44y451_NV_Humboldt_2021_D21.tif

DEM 560/894: USGS_1M_11_x44y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 561/894: USGS_1M_11_x45y415_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 562/894: USGS_1M_11_x45y416_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 563/894: USGS_1M_11_x45y417_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 564/894: USGS_1M_11_x45y418_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 565/894: USGS_1M_11_x45y419_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 566/894: USGS_1M_11_x45y420_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 567/894: USGS_1M_11_x45y421_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 568/894: USGS_1M_11_x45y422_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 569/894: USGS_1M_11_x45y423_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 570/894: USGS_1M_11_x45y424_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 571/894: USGS_1M_11_x45y425_NV_WestCentral_EarthMRI_2020_D20.tif

2026-10-21 23:41:21,305 | ERROR | FAILED | USGS_1M_11_x45y426_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y426_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,309 | ERROR | FAILED | USGS_1M_11_x45y434_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x45y434_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,314 | ERROR | FAILED | USGS_1M_11_x45y435_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x45y435_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,316 | ERROR | FAILED | USGS_1M_11_x45y436_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x45y436_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,318 | ERROR | FAILED | USGS_1M_11_x45y437_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x45y437_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,322 | ERROR | FAILED | USGS_1M_11_x45y438_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x45y438_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,325 | ERROR | FAILED | USGS_1M_11_x45y438_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y438_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,328 | ERROR | FAILED | USGS_1M_11_x45y439_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x45y439_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,331 | ERROR | FAILED | USGS_1M_11_x45y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,333 | ERROR | FAILED | USGS_1M_11_x45y440_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x45y440_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,337 | ERROR | FAILED | USGS_1M_11_x45y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,340 | ERROR | FAILED | USGS_1M_11_x45y441_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x45y441_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,342 | ERROR | FAILED | USGS_1M_11_x45y441_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y441_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,344 | ERROR | FAILED | USGS_1M_11_x45y442_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x45y442_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,347 | ERROR | FAILED | USGS_1M_11_x45y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,349 | ERROR | FAILED | USGS_1M_11_x45y443_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x45y443_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,351 | ERROR | FAILED | USGS_1M_11_x45y443_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y443_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,354 | ERROR | FAILED | USGS_1M_11_x45y444_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x45y444_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,357 | ERROR | FAILED | USGS_1M_11_x45y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,359 | ERROR | FAILED | USGS_1M_11_x45y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,362 | ERROR | FAILED | USGS_1M_11_x45y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,365 | ERROR | FAILED | USGS_1M_11_x45y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,367 | ERROR | FAILED | USGS_1M_11_x45y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,369 | ERROR | FAILED | USGS_1M_11_x45y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,372 | ERROR | FAILED | USGS_1M_11_x45y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,374 | ERROR | FAILED | USGS_1M_11_x45y451_NV_Humboldt_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_Humboldt_2021_D21/USGS_1M_11_x45y451_NV_Humboldt_2021_D21.tif'
2026-10-21 23:41:21,377 | ERROR | FAILED | USGS_1M_11_x45y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x45y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,380 | ERROR | FAILED | USGS_1M_11_x46y416_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y416_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,381 | ERROR | FAILED | USGS_1M_11_x46y417_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y417_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,385 | ERROR | FAILED | USGS_1M_11_x46y418_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y418_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,388 | ERROR | FAILED | USGS_1M_11_x46y419_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y419_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,391 | ERROR | FAILED | USGS_1M_11_x46y420_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y420_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,392 | ERROR | FAILED | USGS_1M_11_x46y421_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y421_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,394 | ERROR | FAILED | USGS_1M_11_x46y422_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y422_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,397 | ERROR | FAILED | USGS_1M_11_x46y423_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y423_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,401 | ERROR | FAILED | USGS_1M_11_x46y434_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x46y434_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,403 | ERROR | FAILED | USGS_1M_11_x46y435_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x46y435_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,407 | ERROR | FAILED | USGS_1M_11_x46y436_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x46y436_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,410 | ERROR | FAILED | USGS_1M_11_x46y437_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x46y437_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,412 | ERROR | FAILED | USGS_1M_11_x46y438_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x46y438_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,416 | ERROR | FAILED | USGS_1M_11_x46y439_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x46y439_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,421 | ERROR | FAILED | USGS_1M_11_x46y439_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y439_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,423 | ERROR | FAILED | USGS_1M_11_x46y440_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x46y440_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,426 | ERROR | FAILED | USGS_1M_11_x46y440_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y440_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,428 | ERROR | FAILED | USGS_1M_11_x46y441_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x46y441_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,430 | ERROR | FAILED | USGS_1M_11_x46y442_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x46y442_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,433 | ERROR | FAILED | USGS_1M_11_x46y442_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y442_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,436 | ERROR | FAILED | USGS_1M_11_x46y443_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x46y443_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,438 | ERROR | FAILED | USGS_1M_11_x46y444_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x46y444_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,441 | ERROR | FAILED | USGS_1M_11_x46y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,443 | ERROR | FAILED | USGS_1M_11_x46y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,447 | ERROR | FAILED | USGS_1M_11_x46y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,451 | ERROR | FAILED | USGS_1M_11_x46y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,452 | ERROR | FAILED | USGS_1M_11_x46y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,455 | ERROR | FAILED | USGS_1M_11_x46y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,458 | ERROR | FAILED | USGS_1M_11_x46y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,459 | ERROR | FAILED | USGS_1M_11_x46y451_NV_Humboldt_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_Humboldt_2021_D21/USGS_1M_11_x46y451_NV_Humboldt_2021_D21.tif'
2026-10-21 23:41:21,464 | ERROR | FAILED | USGS_1M_11_x46y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x46y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,469 | ERROR | FAILED | USGS_1M_11_x47y418_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x47y418_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,470 | ERROR | FAILED | USGS_1M_11_x47y419_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x47y419_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,473 | ERROR | FAILED | USGS_1M_11_x47y420_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x47y420_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,478 | ERROR | FAILED | USGS_1M_11_x47y434_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x47y434_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,480 | ERROR | FAILED | USGS_1M_11_x47y435_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x47y435_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,483 | ERROR | FAILED | USGS_1M_11_x47y436_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x47y436_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,489 | ERROR | FAILED | USGS_1M_11_x47y437_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x47y437_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,490 | ERROR | FAILED | USGS_1M_11_x47y438_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x47y438_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,492 | ERROR | FAILED | USGS_1M_11_x47y439_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x47y439_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,495 | ERROR | FAILED | USGS_1M_11_x47y440_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x47y440_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,499 | ERROR | FAILED | USGS_1M_11_x47y441_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x47y441_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,501 | ERROR | FAILED | USGS_1M_11_x47y442_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x47y442_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,505 | ERROR | FAILED | USGS_1M_11_x47y443_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x47y443_NV_EastCentral_2021_D21.tif'

DEM 572/894: USGS_1M_11_x45y426_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 573/894: USGS_1M_11_x45y434_NV_EastCentral_2021_D21.tif

DEM 574/894: USGS_1M_11_x45y435_NV_EastCentral_2021_D21.tif

DEM 575/894: USGS_1M_11_x45y436_NV_EastCentral_2021_D21.tif

DEM 576/894: USGS_1M_11_x45y437_NV_EastCentral_2021_D21.tif

DEM 577/894: USGS_1M_11_x45y438_NV_EastCentral_2021_D21.tif

DEM 578/894: USGS_1M_11_x45y438_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 579/894: USGS_1M_11_x45y439_NV_EastCentral_2021_D21.tif

DEM 580/894: USGS_1M_11_x45y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 581/894: USGS_1M_11_x45y440_NV_EastCentral_2021_D21.tif

DEM 582/894: USGS_1M_11_x45y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 583/894: USGS_1M_11_x45y441_NV_EastCentral_2021_D21.tif

DEM 584/894: USGS_1M_11_x45y441_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 585/894: USGS_1M_11_x45y442_NV_EastCentral_2021_D21.tif

DEM 586/894: USGS_1M_11_x45y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 587/894: USGS_1M_11_x45y443_NV_EastCentral_2021_D21.tif

DEM 588/894: USGS_1M_11_x45y443_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 589/894: USGS_1M_11_x45y444_NV_EastCentral_2021_D21.tif

DEM 590/894: USGS_1M_11_x45y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 591/894: USGS_1M_11_x45y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 592/894: USGS_1M_11_x45y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 593/894: USGS_1M_11_x45y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 594/894: USGS_1M_11_x45y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 595/894: USGS_1M_11_x45y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 596/894: USGS_1M_11_x45y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 597/894: USGS_1M_11_x45y451_NV_Humboldt_2021_D21.tif

DEM 598/894: USGS_1M_11_x45y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 599/894: USGS_1M_11_x46y416_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 600/894: USGS_1M_11_x46y417_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 601/894: USGS_1M_11_x46y418_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 602/894: USGS_1M_11_x46y419_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 603/894: USGS_1M_11_x46y420_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 604/894: USGS_1M_11_x46y421_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 605/894: USGS_1M_11_x46y422_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 606/894: USGS_1M_11_x46y423_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 607/894: USGS_1M_11_x46y434_NV_EastCentral_2021_D21.tif

DEM 608/894: USGS_1M_11_x46y435_NV_EastCentral_2021_D21.tif

DEM 609/894: USGS_1M_11_x46y436_NV_EastCentral_2021_D21.tif

DEM 610/894: USGS_1M_11_x46y437_NV_EastCentral_2021_D21.tif

DEM 611/894: USGS_1M_11_x46y438_NV_EastCentral_2021_D21.tif

DEM 612/894: USGS_1M_11_x46y439_NV_EastCentral_2021_D21.tif

DEM 613/894: USGS_1M_11_x46y439_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 614/894: USGS_1M_11_x46y440_NV_EastCentral_2021_D21.tif

DEM 615/894: USGS_1M_11_x46y440_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 616/894: USGS_1M_11_x46y441_NV_EastCentral_2021_D21.tif

DEM 617/894: USGS_1M_11_x46y442_NV_EastCentral_2021_D21.tif

DEM 618/894: USGS_1M_11_x46y442_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 619/894: USGS_1M_11_x46y443_NV_EastCentral_2021_D21.tif

DEM 620/894: USGS_1M_11_x46y444_NV_EastCentral_2021_D21.tif

DEM 621/894: USGS_1M_11_x46y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 622/894: USGS_1M_11_x46y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 623/894: USGS_1M_11_x46y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 624/894: USGS_1M_11_x46y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 625/894: USGS_1M_11_x46y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 626/894: USGS_1M_11_x46y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 627/894: USGS_1M_11_x46y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 628/894: USGS_1M_11_x46y451_NV_Humboldt_2021_D21.tif

DEM 629/894: USGS_1M_11_x46y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 630/894: USGS_1M_11_x47y418_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 631/894: USGS_1M_11_x47y419_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 632/894: USGS_1M_11_x47y420_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 633/894: USGS_1M_11_x47y434_NV_EastCentral_2021_D21.tif

DEM 634/894: USGS_1M_11_x47y435_NV_EastCentral_2021_D21.tif

DEM 635/894: USGS_1M_11_x47y436_NV_EastCentral_2021_D21.tif

DEM 636/894: USGS_1M_11_x47y437_NV_EastCentral_2021_D21.tif

DEM 637/894: USGS_1M_11_x47y438_NV_EastCentral_2021_D21.tif

DEM 638/894: USGS_1M_11_x47y439_NV_EastCentral_2021_D21.tif

DEM 639/894: USGS_1M_11_x47y440_NV_EastCentral_2021_D21.tif

DEM 640/894: USGS_1M_11_x47y441_NV_EastCentral_2021_D21.tif

DEM 641/894: USGS_1M_11_x47y442_NV_EastCentral_2021_D21.tif

DEM 642/894: USGS_1M_11_x47y443_NV_EastCentral_2021_D21.tif

2026-10-21 23:41:21,510 | ERROR | FAILED | USGS_1M_11_x47y444_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x47y444_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,513 | ERROR | FAILED | USGS_1M_11_x47y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x47y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,515 | ERROR | FAILED | USGS_1M_11_x47y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x47y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,518 | ERROR | FAILED | USGS_1M_11_x47y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x47y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,520 | ERROR | FAILED | USGS_1M_11_x47y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x47y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,523 | ERROR | FAILED | USGS_1M_11_x47y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x47y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,527 | ERROR | FAILED | USGS_1M_11_x47y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x47y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,533 | ERROR | FAILED | USGS_1M_11_x47y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x47y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,535 | ERROR | FAILED | USGS_1M_11_x47y451_NV_Humboldt_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_Humboldt_2021_D21/USGS_1M_11_x47y451_NV_Humboldt_2021_D21.tif'
2026-10-21 23:41:21,540 | ERROR | FAILED | USGS_1M_11_x47y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x47y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,542 | ERROR | FAILED | USGS_1M_11_x48y434_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x48y434_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,547 | ERROR | FAILED | USGS_1M_11_x48y435_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x48y435_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,551 | ERROR | FAILED | USGS_1M_11_x48y436_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x48y436_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,558 | ERROR | FAILED | USGS_1M_11_x48y437_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x48y437_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,567 | ERROR | FAILED | USGS_1M_11_x48y438_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x48y438_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,568 | ERROR | FAILED | USGS_1M_11_x48y439_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x48y439_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,574 | ERROR | FAILED | USGS_1M_11_x48y440_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x48y440_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,581 | ERROR | FAILED | USGS_1M_11_x48y441_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x48y441_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,584 | ERROR | FAILED | USGS_1M_11_x48y442_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x48y442_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,592 | ERROR | FAILED | USGS_1M_11_x48y443_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x48y443_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,593 | ERROR | FAILED | USGS_1M_11_x48y444_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x48y444_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,595 | ERROR | FAILED | USGS_1M_11_x48y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x48y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,597 | ERROR | FAILED | USGS_1M_11_x48y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x48y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,597 | ERROR | FAILED | USGS_1M_11_x48y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x48y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,599 | ERROR | FAILED | USGS_1M_11_x48y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x48y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,600 | ERROR | FAILED | USGS_1M_11_x48y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x48y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,602 | ERROR | FAILED | USGS_1M_11_x48y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x48y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,604 | ERROR | FAILED | USGS_1M_11_x48y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x48y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,605 | ERROR | FAILED | USGS_1M_11_x48y451_NV_Humboldt_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_Humboldt_2021_D21/USGS_1M_11_x48y451_NV_Humboldt_2021_D21.tif'
2026-10-21 23:41:21,609 | ERROR | FAILED | USGS_1M_11_x48y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x48y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,612 | ERROR | FAILED | USGS_1M_11_x49y434_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x49y434_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,615 | ERROR | FAILED | USGS_1M_11_x49y435_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x49y435_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,616 | ERROR | FAILED | USGS_1M_11_x49y436_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x49y436_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,619 | ERROR | FAILED | USGS_1M_11_x49y437_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x49y437_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,620 | ERROR | FAILED | USGS_1M_11_x49y438_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x49y438_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,621 | ERROR | FAILED | USGS_1M_11_x49y439_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x49y439_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,622 | ERROR | FAILED | USGS_1M_11_x49y440_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x49y440_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,623 | ERROR | FAILED | USGS_1M_11_x49y441_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x49y441_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,624 | ERROR | FAILED | USGS_1M_11_x49y442_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x49y442_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,625 | ERROR | FAILED | USGS_1M_11_x49y443_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x49y443_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,627 | ERROR | FAILED | USGS_1M_11_x49y444_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x49y444_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,628 | ERROR | FAILED | USGS_1M_11_x49y444_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x49y444_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,631 | ERROR | FAILED | USGS_1M_11_x49y444_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x49y444_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,632 | ERROR | FAILED | USGS_1M_11_x49y445_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x49y445_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,635 | ERROR | FAILED | USGS_1M_11_x49y445_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x49y445_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,636 | ERROR | FAILED | USGS_1M_11_x49y446_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x49y446_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,639 | ERROR | FAILED | USGS_1M_11_x49y446_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x49y446_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,639 | ERROR | FAILED | USGS_1M_11_x49y447_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x49y447_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,641 | ERROR | FAILED | USGS_1M_11_x49y447_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x49y447_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,642 | ERROR | FAILED | USGS_1M_11_x49y448_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x49y448_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,644 | ERROR | FAILED | USGS_1M_11_x49y448_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x49y448_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,647 | ERROR | FAILED | USGS_1M_11_x49y449_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x49y449_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,652 | ERROR | FAILED | USGS_1M_11_x49y449_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x49y449_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,654 | ERROR | FAILED | USGS_1M_11_x49y450_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x49y450_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,657 | ERROR | FAILED | USGS_1M_11_x49y450_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x49y450_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,657 | ERROR | FAILED | USGS_1M_11_x49y451_NV_Humboldt_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_Humboldt_2021_D21/USGS_1M_11_x49y451_NV_Humboldt_2021_D21.tif'
2026-10-21 23:41:21,659 | ERROR | FAILED | USGS_1M_11_x49y451_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x49y451_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,659 | ERROR | FAILED | USGS_1M_11_x49y451_NV_WestCentral_EarthMRI_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_WestCentral_EarthMRI_2020_D20/USGS_1M_11_x49y451_NV_WestCentral_EarthMRI_2020_D20.tif'
2026-10-21 23:41:21,661 | ERROR | FAILED | USGS_1M_11_x50y434_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x50y434_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,663 | ERROR | FAILED | USGS_1M_11_x50y435_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x50y435_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,668 | ERROR | FAILED | USGS_1M_11_x50y436_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x50y436_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,669 | ERROR | FAILED | USGS_1M_11_x50y437_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x50y437_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,670 | ERROR | FAILED | USGS_1M_11_x50y438_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x50y438_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,671 | ERROR | FAILED | USGS_1M_11_x50y439_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x50y439_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,673 | ERROR | FAILED | USGS_1M_11_x50y440_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x50y440_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,674 | ERROR | FAILED | USGS_1M_11_x50y441_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x50y441_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,675 | ERROR | FAILED | USGS_1M_11_x50y442_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x50y442_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,676 | ERROR | FAILED | USGS_1M_11_x50y443_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x50y443_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,677 | ERROR | FAILED | USGS_1M_11_x50y444_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x50y444_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,678 | ERROR | FAILED | USGS_1M_11_x50y444_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x50y444_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,679 | ERROR | FAILED | USGS_1M_11_x50y445_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x50y445_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,680 | ERROR | FAILED | USGS_1M_11_x50y446_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x50y446_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,682 | ERROR | FAILED | USGS_1M_11_x50y447_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x50y447_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,685 | ERROR | FAILED | USGS_1M_11_x50y448_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x50y448_NV_NorthWestElko_2020_D20.tif'

DEM 643/894: USGS_1M_11_x47y444_NV_EastCentral_2021_D21.tif

DEM 644/894: USGS_1M_11_x47y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 645/894: USGS_1M_11_x47y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 646/894: USGS_1M_11_x47y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 647/894: USGS_1M_11_x47y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 648/894: USGS_1M_11_x47y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 649/894: USGS_1M_11_x47y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 650/894: USGS_1M_11_x47y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 651/894: USGS_1M_11_x47y451_NV_Humboldt_2021_D21.tif

DEM 652/894: USGS_1M_11_x47y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 653/894: USGS_1M_11_x48y434_NV_EastCentral_2021_D21.tif

DEM 654/894: USGS_1M_11_x48y435_NV_EastCentral_2021_D21.tif

DEM 655/894: USGS_1M_11_x48y436_NV_EastCentral_2021_D21.tif

DEM 656/894: USGS_1M_11_x48y437_NV_EastCentral_2021_D21.tif

DEM 657/894: USGS_1M_11_x48y438_NV_EastCentral_2021_D21.tif

DEM 658/894: USGS_1M_11_x48y439_NV_EastCentral_2021_D21.tif

DEM 659/894: USGS_1M_11_x48y440_NV_EastCentral_2021_D21.tif

DEM 660/894: USGS_1M_11_x48y441_NV_EastCentral_2021_D21.tif

DEM 661/894: USGS_1M_11_x48y442_NV_EastCentral_2021_D21.tif

DEM 662/894: USGS_1M_11_x48y443_NV_EastCentral_2021_D21.tif

DEM 663/894: USGS_1M_11_x48y444_NV_EastCentral_2021_D21.tif

DEM 664/894: USGS_1M_11_x48y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 665/894: USGS_1M_11_x48y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 666/894: USGS_1M_11_x48y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 667/894: USGS_1M_11_x48y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 668/894: USGS_1M_11_x48y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 669/894: USGS_1M_11_x48y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 670/894: USGS_1M_11_x48y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 671/894: USGS_1M_11_x48y451_NV_Humboldt_2021_D21.tif

DEM 672/894: USGS_1M_11_x48y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 673/894: USGS_1M_11_x49y434_NV_EastCentral_2021_D21.tif

DEM 674/894: USGS_1M_11_x49y435_NV_EastCentral_2021_D21.tif

DEM 675/894: USGS_1M_11_x49y436_NV_EastCentral_2021_D21.tif

DEM 676/894: USGS_1M_11_x49y437_NV_EastCentral_2021_D21.tif

DEM 677/894: USGS_1M_11_x49y438_NV_EastCentral_2021_D21.tif

DEM 678/894: USGS_1M_11_x49y439_NV_EastCentral_2021_D21.tif

DEM 679/894: USGS_1M_11_x49y440_NV_EastCentral_2021_D21.tif

DEM 680/894: USGS_1M_11_x49y441_NV_EastCentral_2021_D21.tif

DEM 681/894: USGS_1M_11_x49y442_NV_EastCentral_2021_D21.tif

DEM 682/894: USGS_1M_11_x49y443_NV_EastCentral_2021_D21.tif

DEM 683/894: USGS_1M_11_x49y444_NV_EastCentral_2021_D21.tif

DEM 684/894: USGS_1M_11_x49y444_NV_NorthWestElko_2020_D20.tif

DEM 685/894: USGS_1M_11_x49y444_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 686/894: USGS_1M_11_x49y445_NV_NorthWestElko_2020_D20.tif

DEM 687/894: USGS_1M_11_x49y445_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 688/894: USGS_1M_11_x49y446_NV_NorthWestElko_2020_D20.tif

DEM 689/894: USGS_1M_11_x49y446_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 690/894: USGS_1M_11_x49y447_NV_NorthWestElko_2020_D20.tif

DEM 691/894: USGS_1M_11_x49y447_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 692/894: USGS_1M_11_x49y448_NV_NorthWestElko_2020_D20.tif

DEM 693/894: USGS_1M_11_x49y448_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 694/894: USGS_1M_11_x49y449_NV_NorthWestElko_2020_D20.tif

DEM 695/894: USGS_1M_11_x49y449_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 696/894: USGS_1M_11_x49y450_NV_NorthWestElko_2020_D20.tif

DEM 697/894: USGS_1M_11_x49y450_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 698/894: USGS_1M_11_x49y451_NV_Humboldt_2021_D21.tif

DEM 699/894: USGS_1M_11_x49y451_NV_NorthWestElko_2020_D20.tif

DEM 700/894: USGS_1M_11_x49y451_NV_WestCentral_EarthMRI_2020_D20.tif

DEM 701/894: USGS_1M_11_x50y434_NV_EastCentral_2021_D21.tif

DEM 702/894: USGS_1M_11_x50y435_NV_EastCentral_2021_D21.tif

DEM 703/894: USGS_1M_11_x50y436_NV_EastCentral_2021_D21.tif

DEM 704/894: USGS_1M_11_x50y437_NV_EastCentral_2021_D21.tif

DEM 705/894: USGS_1M_11_x50y438_NV_EastCentral_2021_D21.tif

DEM 706/894: USGS_1M_11_x50y439_NV_EastCentral_2021_D21.tif

DEM 707/894: USGS_1M_11_x50y440_NV_EastCentral_2021_D21.tif

DEM 708/894: USGS_1M_11_x50y441_NV_EastCentral_2021_D21.tif

DEM 709/894: USGS_1M_11_x50y442_NV_EastCentral_2021_D21.tif

DEM 710/894: USGS_1M_11_x50y443_NV_EastCentral_2021_D21.tif

DEM 711/894: USGS_1M_11_x50y444_NV_EastCentral_2021_D21.tif

DEM 712/894: USGS_1M_11_x50y444_NV_NorthWestElko_2020_D20.tif

DEM 713/894: USGS_1M_11_x50y445_NV_NorthWestElko_2020_D20.tif

DEM 714/894: USGS_1M_11_x50y446_NV_NorthWestElko_2020_D20.tif

DEM 715/894: USGS_1M_11_x50y447_NV_NorthWestElko_2020_D20.tif

DEM 716/894: USGS_1M_11_x50y448_NV_NorthWestElko_2020_D20.tif

DEM 717/894: USGS_1M_11_x50y449_NV_NorthWestElko_2020_D20.tif

DEM 718/894: USGS_1M_11_x50y450_NV_NorthWestElko_2020_D20.tif

DEM 719/894: USGS_1M_11_x50y451_NV_NorthWestElko_2020_D20.tif

DEM 720/894: USGS_1M_11_x51y434_NV_EastCentral_2021_D21.tif

DEM 721/894: USGS_1M_11_x51y435_NV_EastCentral_2021_D21.tif

DEM 722/894: USGS_1M_11_x51y436_NV_EastCentral_2021_D21.tif

DEM 723/894: USGS_1M_11_x51y437_NV_EastCentral_2021_D21.tif

2026-10-21 23:41:21,717 | ERROR | FAILED | USGS_1M_11_x51y438_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x51y438_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,728 | ERROR | FAILED | USGS_1M_11_x51y439_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x51y439_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,730 | ERROR | FAILED | USGS_1M_11_x51y440_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x51y440_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,738 | ERROR | FAILED | USGS_1M_11_x51y441_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x51y441_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,744 | ERROR | FAILED | USGS_1M_11_x51y442_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x51y442_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,747 | ERROR | FAILED | USGS_1M_11_x51y443_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x51y443_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,750 | ERROR | FAILED | USGS_1M_11_x51y444_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x51y444_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,753 | ERROR | FAILED | USGS_1M_11_x51y444_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x51y444_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,756 | ERROR | FAILED | USGS_1M_11_x51y445_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x51y445_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,760 | ERROR | FAILED | USGS_1M_11_x51y446_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x51y446_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,763 | ERROR | FAILED | USGS_1M_11_x51y447_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x51y447_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,766 | ERROR | FAILED | USGS_1M_11_x51y448_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x51y448_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,768 | ERROR | FAILED | USGS_1M_11_x51y449_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x51y449_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,771 | ERROR | FAILED | USGS_1M_11_x51y450_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x51y450_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,776 | ERROR | FAILED | USGS_1M_11_x51y451_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x51y451_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,778 | ERROR | FAILED | USGS_1M_11_x52y434_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x52y434_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,782 | ERROR | FAILED | USGS_1M_11_x52y435_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x52y435_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,784 | ERROR | FAILED | USGS_1M_11_x52y436_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x52y436_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,789 | ERROR | FAILED | USGS_1M_11_x52y437_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x52y437_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,791 | ERROR | FAILED | USGS_1M_11_x52y438_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x52y438_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,793 | ERROR | FAILED | USGS_1M_11_x52y439_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x52y439_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,795 | ERROR | FAILED | USGS_1M_11_x52y440_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x52y440_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,797 | ERROR | FAILED | USGS_1M_11_x52y441_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x52y441_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,800 | ERROR | FAILED | USGS_1M_11_x52y442_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x52y442_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,804 | ERROR | FAILED | USGS_1M_11_x52y443_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x52y443_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,807 | ERROR | FAILED | USGS_1M_11_x52y444_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x52y444_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,809 | ERROR | FAILED | USGS_1M_11_x52y444_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x52y444_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,812 | ERROR | FAILED | USGS_1M_11_x52y445_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x52y445_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,815 | ERROR | FAILED | USGS_1M_11_x52y446_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x52y446_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,818 | ERROR | FAILED | USGS_1M_11_x52y447_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x52y447_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,820 | ERROR | FAILED | USGS_1M_11_x52y448_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x52y448_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,821 | ERROR | FAILED | USGS_1M_11_x52y449_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x52y449_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,825 | ERROR | FAILED | USGS_1M_11_x52y450_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x52y450_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,828 | ERROR | FAILED | USGS_1M_11_x52y451_NV_NorthWestElko_2020_D20.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x52y451_NV_NorthWestElko_2020_D20.tif'
2026-10-21 23:41:21,831 | ERROR | FAILED | USGS_1M_11_x53y434_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y434_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,836 | ERROR | FAILED | USGS_1M_11_x53y435_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y435_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,839 | ERROR | FAILED | USGS_1M_11_x53y436_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y436_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,842 | ERROR | FAILED | USGS_1M_11_x53y437_NV_EastCentral_2021_D21.tif | [Errno 107] Transport endpoint is not connected: '/content/drive/MyDrive/GEMS_2/data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y437_NV_EastCentral_2021_D21.tif'
2026-10-21 23:41:21,854 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y438_NV_EastCentral_2021_D21.tif

DEM 724/894: USGS_1M_11_x51y438_NV_EastCentral_2021_D21.tif

DEM 725/894: USGS_1M_11_x51y439_NV_EastCentral_2021_D21.tif

DEM 726/894: USGS_1M_11_x51y440_NV_EastCentral_2021_D21.tif

DEM 727/894: USGS_1M_11_x51y441_NV_EastCentral_2021_D21.tif

DEM 728/894: USGS_1M_11_x51y442_NV_EastCentral_2021_D21.tif

DEM 729/894: USGS_1M_11_x51y443_NV_EastCentral_2021_D21.tif

DEM 730/894: USGS_1M_11_x51y444_NV_EastCentral_2021_D21.tif

DEM 731/894: USGS_1M_11_x51y444_NV_NorthWestElko_2020_D20.tif

DEM 732/894: USGS_1M_11_x51y445_NV_NorthWestElko_2020_D20.tif

DEM 733/894: USGS_1M_11_x51y446_NV_NorthWestElko_2020_D20.tif

DEM 734/894: USGS_1M_11_x51y447_NV_NorthWestElko_2020_D20.tif

DEM 735/894: USGS_1M_11_x51y448_NV_NorthWestElko_2020_D20.tif

DEM 736/894: USGS_1M_11_x51y449_NV_NorthWestElko_2020_D20.tif

DEM 737/894: USGS_1M_11_x51y450_NV_NorthWestElko_2020_D20.tif

DEM 738/894: USGS_1M_11_x51y451_NV_NorthWestElko_2020_D20.tif

DEM 739/894: USGS_1M_11_x52y434_NV_EastCentral_2021_D21.tif

DEM 740/894: USGS_1M_11_x52y435_NV_EastCentral_2021_D21.tif

DEM 741/894: USGS_1M_11_x52y436_NV_EastCentral_2021_D21.tif

DEM 742/894: USGS_1M_11_x52y437_NV_EastCentral_2021_D21.tif

DEM 743/894: USGS_1M_11_x52y438_NV_EastCentral_2021_D21.tif

DEM 744/894: USGS_1M_11_x52y439_NV_EastCentral_2021_D21.tif

DEM 745/894: USGS_1M_11_x52y440_NV_EastCentral_2021_D21.tif

DEM 746/894: USGS_1M_11_x52y441_NV_EastCentral_2021_D21.tif

DEM 747/894: USGS_1M_11_x52y442_NV_EastCentral_2021_D21.tif

DEM 748/894: USGS_1M_11_x52y443_NV_EastCentral_2021_D21.tif

DEM 749/894: USGS_1M_11_x52y444_NV_EastCentral_2021_D21.tif

DEM 750/894: USGS_1M_11_x52y444_NV_NorthWestElko_2020_D20.tif

DEM 751/894: USGS_1M_11_x52y445_NV_NorthWestElko_2020_D20.tif

DEM 752/894: USGS_1M_11_x52y446_NV_NorthWestElko_2020_D20.tif

DEM 753/894: USGS_1M_11_x52y447_NV_NorthWestElko_2020_D20.tif

DEM 754/894: USGS_1M_11_x52y448_NV_NorthWestElko_2020_D20.tif

DEM 755/894: USGS_1M_11_x52y449_NV_NorthWestElko_2020_D20.tif

DEM 756/894: USGS_1M_11_x52y450_NV_NorthWestElko_2020_D20.tif

DEM 757/894: USGS_1M_11_x52y451_NV_NorthWestElko_2020_D20.tif

DEM 758/894: USGS_1M_11_x53y434_NV_EastCentral_2021_D21.tif

DEM 759/894: USGS_1M_11_x53y435_NV_EastCentral_2021_D21.tif

DEM 760/894: USGS_1M_11_x53y436_NV_EastCentral_2021_D21.tif

DEM 761/894: USGS_1M_11_x53y437_NV_EastCentral_2021_D21.tif

DEM 762/894: USGS_1M_11_x53y438_NV_EastCentral_2021_D21.tif

2026-10-21 23:41:35,119 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y438_NV_EastCentral_2021_D21.tif (244.73 MB)
2026-10-21 23:41:35,186 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y439_NV_EastCentral_2021_D21.tif

DEM 763/894: USGS_1M_11_x53y439_NV_EastCentral_2021_D21.tif

2026-10-21 23:41:54,117 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y439_NV_EastCentral_2021_D21.tif (267.26 MB)
2026-10-21 23:41:54,199 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y440_NV_EastCentral_2021_D21.tif

DEM 764/894: USGS_1M_11_x53y440_NV_EastCentral_2021_D21.tif

2026-10-21 23:42:11,531 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y440_NV_EastCentral_2021_D21.tif (268.67 MB)
2026-10-21 23:42:11,578 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y441_NV_EastCentral_2021_D21.tif

DEM 765/894: USGS_1M_11_x53y441_NV_EastCentral_2021_D21.tif

2026-10-21 23:42:39,924 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y441_NV_EastCentral_2021_D21.tif (270.59 MB)
2026-10-21 23:42:39,969 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y442_NV_EastCentral_2021_D21.tif

DEM 766/894: USGS_1M_11_x53y442_NV_EastCentral_2021_D21.tif

2026-10-21 23:43:00,177 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y442_NV_EastCentral_2021_D21.tif (255.34 MB)
2026-10-21 23:43:00,241 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y443_NV_EastCentral_2021_D21.tif

DEM 767/894: USGS_1M_11_x53y443_NV_EastCentral_2021_D21.tif

2026-10-21 23:43:21,449 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y443_NV_EastCentral_2021_D21.tif (248.88 MB)
2026-10-21 23:43:21,494 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y444_NV_EastCentral_2021_D21.tif

DEM 768/894: USGS_1M_11_x53y444_NV_EastCentral_2021_D21.tif

2026-10-21 23:43:23,898 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x53y444_NV_EastCentral_2021_D21.tif (24.18 MB)
2026-10-21 23:43:23,908 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y444_NV_NorthWestElko_2020_D20.tif

DEM 769/894: USGS_1M_11_x53y444_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:43:45,800 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y444_NV_NorthWestElko_2020_D20.tif (237.98 MB)
2026-10-21 23:43:45,843 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y445_NV_NorthWestElko_2020_D20.tif

DEM 770/894: USGS_1M_11_x53y445_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:44:06,477 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y445_NV_NorthWestElko_2020_D20.tif (285.97 MB)
2026-10-21 23:44:06,521 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y446_NV_NorthWestElko_2020_D20.tif

DEM 771/894: USGS_1M_11_x53y446_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:44:22,578 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y446_NV_NorthWestElko_2020_D20.tif (261.23 MB)
2026-10-21 23:44:22,653 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y447_NV_NorthWestElko_2020_D20.tif

DEM 772/894: USGS_1M_11_x53y447_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:44:36,275 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y447_NV_NorthWestElko_2020_D20.tif (240.53 MB)
2026-10-21 23:44:36,360 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y448_NV_NorthWestElko_2020_D20.tif

DEM 773/894: USGS_1M_11_x53y448_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:44:48,834 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y448_NV_NorthWestElko_2020_D20.tif (242.99 MB)
2026-10-21 23:44:48,891 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y449_NV_NorthWestElko_2020_D20.tif

DEM 774/894: USGS_1M_11_x53y449_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:45:03,492 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y449_NV_NorthWestElko_2020_D20.tif (258.34 MB)
2026-10-21 23:45:03,595 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y450_NV_NorthWestElko_2020_D20.tif

DEM 775/894: USGS_1M_11_x53y450_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:45:15,758 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y450_NV_NorthWestElko_2020_D20.tif (266.45 MB)
2026-10-21 23:45:15,828 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y451_NV_NorthWestElko_2020_D20.tif

DEM 776/894: USGS_1M_11_x53y451_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:45:28,062 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x53y451_NV_NorthWestElko_2020_D20.tif (268.12 MB)
2026-10-21 23:45:28,130 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y435_NV_EastCentral_2021_D21.tif

DEM 777/894: USGS_1M_11_x54y435_NV_EastCentral_2021_D21.tif

2026-10-21 23:45:42,035 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y435_NV_EastCentral_2021_D21.tif (265.81 MB)
2026-10-21 23:45:42,084 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y436_NV_EastCentral_2021_D21.tif

DEM 778/894: USGS_1M_11_x54y436_NV_EastCentral_2021_D21.tif

2026-10-21 23:46:09,259 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y436_NV_EastCentral_2021_D21.tif (271.99 MB)
2026-10-21 23:46:09,339 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y437_NV_EastCentral_2021_D21.tif

DEM 779/894: USGS_1M_11_x54y437_NV_EastCentral_2021_D21.tif

2026-10-21 23:46:37,166 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y437_NV_EastCentral_2021_D21.tif (270.78 MB)
2026-10-21 23:46:37,230 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y438_NV_EastCentral_2021_D21.tif

DEM 780/894: USGS_1M_11_x54y438_NV_EastCentral_2021_D21.tif

2026-10-21 23:47:03,087 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y438_NV_EastCentral_2021_D21.tif (252.47 MB)
2026-10-21 23:47:03,176 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y439_NV_EastCentral_2021_D21.tif

DEM 781/894: USGS_1M_11_x54y439_NV_EastCentral_2021_D21.tif

2026-10-21 23:47:25,529 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y439_NV_EastCentral_2021_D21.tif (251.25 MB)
2026-10-21 23:47:25,577 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y440_NV_EastCentral_2021_D21.tif

DEM 782/894: USGS_1M_11_x54y440_NV_EastCentral_2021_D21.tif

2026-10-21 23:48:04,269 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y440_NV_EastCentral_2021_D21.tif (249.31 MB)
2026-10-21 23:48:04,312 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y441_NV_EastCentral_2021_D21.tif

DEM 783/894: USGS_1M_11_x54y441_NV_EastCentral_2021_D21.tif

2026-10-21 23:48:26,291 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y441_NV_EastCentral_2021_D21.tif (256.76 MB)
2026-10-21 23:48:26,350 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y442_NV_EastCentral_2021_D21.tif

DEM 784/894: USGS_1M_11_x54y442_NV_EastCentral_2021_D21.tif

2026-10-21 23:48:39,979 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y442_NV_EastCentral_2021_D21.tif (259.12 MB)
2026-10-21 23:48:40,032 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y443_NV_EastCentral_2021_D21.tif

DEM 785/894: USGS_1M_11_x54y443_NV_EastCentral_2021_D21.tif

2026-10-21 23:48:54,220 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y443_NV_EastCentral_2021_D21.tif (271.12 MB)
2026-10-21 23:48:54,293 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y444_NV_EastCentral_2021_D21.tif

DEM 786/894: USGS_1M_11_x54y444_NV_EastCentral_2021_D21.tif

2026-10-21 23:48:55,728 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x54y444_NV_EastCentral_2021_D21.tif (25.33 MB)
2026-10-21 23:48:55,742 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y444_NV_NorthWestElko_2020_D20.tif

DEM 787/894: USGS_1M_11_x54y444_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:49:08,410 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y444_NV_NorthWestElko_2020_D20.tif (241.94 MB)
2026-10-21 23:49:08,467 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y445_NV_NorthWestElko_2020_D20.tif

DEM 788/894: USGS_1M_11_x54y445_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:49:21,018 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y445_NV_NorthWestElko_2020_D20.tif (263.09 MB)
2026-10-21 23:49:21,101 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y446_NV_NorthWestElko_2020_D20.tif

DEM 789/894: USGS_1M_11_x54y446_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:49:33,079 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y446_NV_NorthWestElko_2020_D20.tif (283.81 MB)
2026-10-21 23:49:33,154 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y447_NV_NorthWestElko_2020_D20.tif

DEM 790/894: USGS_1M_11_x54y447_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:49:43,783 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y447_NV_NorthWestElko_2020_D20.tif (253.25 MB)
2026-10-21 23:49:43,834 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y448_NV_NorthWestElko_2020_D20.tif

DEM 791/894: USGS_1M_11_x54y448_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:49:57,139 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y448_NV_NorthWestElko_2020_D20.tif (257.76 MB)
2026-10-21 23:49:57,193 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y449_NV_NorthWestElko_2020_D20.tif

DEM 792/894: USGS_1M_11_x54y449_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:50:08,898 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y449_NV_NorthWestElko_2020_D20.tif (250.88 MB)
2026-10-21 23:50:08,948 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y450_NV_NorthWestElko_2020_D20.tif

DEM 793/894: USGS_1M_11_x54y450_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:50:21,322 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y450_NV_NorthWestElko_2020_D20.tif (263.80 MB)
2026-10-21 23:50:21,377 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y451_NV_NorthWestElko_2020_D20.tif

DEM 794/894: USGS_1M_11_x54y451_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:50:34,155 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x54y451_NV_NorthWestElko_2020_D20.tif (263.19 MB)
2026-10-21 23:50:34,215 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y437_NV_EastCentral_2021_D21.tif

DEM 795/894: USGS_1M_11_x55y437_NV_EastCentral_2021_D21.tif

2026-10-21 23:50:46,018 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y437_NV_EastCentral_2021_D21.tif (256.51 MB)
2026-10-21 23:50:46,125 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y438_NV_EastCentral_2021_D21.tif

DEM 796/894: USGS_1M_11_x55y438_NV_EastCentral_2021_D21.tif

2026-10-21 23:50:56,464 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y438_NV_EastCentral_2021_D21.tif (250.28 MB)
2026-10-21 23:50:56,510 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y439_NV_EastCentral_2021_D21.tif

DEM 797/894: USGS_1M_11_x55y439_NV_EastCentral_2021_D21.tif

2026-10-21 23:51:07,434 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y439_NV_EastCentral_2021_D21.tif (249.22 MB)
2026-10-21 23:51:07,483 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y440_NV_EastCentral_2021_D21.tif

DEM 798/894: USGS_1M_11_x55y440_NV_EastCentral_2021_D21.tif

2026-10-21 23:51:18,727 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y440_NV_EastCentral_2021_D21.tif (253.33 MB)
2026-10-21 23:51:18,783 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y441_NV_EastCentral_2021_D21.tif

DEM 799/894: USGS_1M_11_x55y441_NV_EastCentral_2021_D21.tif

2026-10-21 23:51:44,627 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y441_NV_EastCentral_2021_D21.tif (270.55 MB)
2026-10-21 23:51:44,663 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y442_NV_EastCentral_2021_D21.tif

DEM 800/894: USGS_1M_11_x55y442_NV_EastCentral_2021_D21.tif

2026-10-21 23:52:06,133 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y442_NV_EastCentral_2021_D21.tif (276.45 MB)
2026-10-21 23:52:06,295 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y443_NV_EastCentral_2021_D21.tif

DEM 801/894: USGS_1M_11_x55y443_NV_EastCentral_2021_D21.tif

2026-10-21 23:52:18,557 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y443_NV_EastCentral_2021_D21.tif (262.30 MB)
2026-10-21 23:52:18,606 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y444_NV_EastCentral_2021_D21.tif

DEM 802/894: USGS_1M_11_x55y444_NV_EastCentral_2021_D21.tif

2026-10-21 23:52:19,325 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x55y444_NV_EastCentral_2021_D21.tif (24.34 MB)
2026-10-21 23:52:19,334 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y444_NV_NorthWestElko_2020_D20.tif

DEM 803/894: USGS_1M_11_x55y444_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:52:30,871 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y444_NV_NorthWestElko_2020_D20.tif (247.41 MB)
2026-10-21 23:52:30,916 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y445_NV_NorthWestElko_2020_D20.tif

DEM 804/894: USGS_1M_11_x55y445_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:52:46,495 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y445_NV_NorthWestElko_2020_D20.tif (264.31 MB)
2026-10-21 23:52:46,543 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y446_NV_NorthWestElko_2020_D20.tif

DEM 805/894: USGS_1M_11_x55y446_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:52:59,206 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y446_NV_NorthWestElko_2020_D20.tif (270.39 MB)
2026-10-21 23:52:59,255 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y447_NV_NorthWestElko_2020_D20.tif

DEM 806/894: USGS_1M_11_x55y447_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:53:11,954 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y447_NV_NorthWestElko_2020_D20.tif (275.56 MB)
2026-10-21 23:53:12,029 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y448_NV_NorthWestElko_2020_D20.tif

DEM 807/894: USGS_1M_11_x55y448_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:53:23,260 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y448_NV_NorthWestElko_2020_D20.tif (253.07 MB)
2026-10-21 23:53:23,330 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y449_NV_NorthWestElko_2020_D20.tif

DEM 808/894: USGS_1M_11_x55y449_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:53:35,112 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y449_NV_NorthWestElko_2020_D20.tif (269.44 MB)
2026-10-21 23:53:35,166 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y450_NV_NorthWestElko_2020_D20.tif

DEM 809/894: USGS_1M_11_x55y450_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:53:46,633 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y450_NV_NorthWestElko_2020_D20.tif (272.72 MB)
2026-10-21 23:53:46,685 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y451_NV_NorthWestElko_2020_D20.tif

DEM 810/894: USGS_1M_11_x55y451_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:53:58,665 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x55y451_NV_NorthWestElko_2020_D20.tif (279.52 MB)
2026-10-21 23:53:58,716 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x56y440_NV_EastCentral_2021_D21.tif

DEM 811/894: USGS_1M_11_x56y440_NV_EastCentral_2021_D21.tif

2026-10-21 23:54:11,052 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x56y440_NV_EastCentral_2021_D21.tif (256.61 MB)
2026-10-21 23:54:11,102 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x56y441_NV_EastCentral_2021_D21.tif

DEM 812/894: USGS_1M_11_x56y441_NV_EastCentral_2021_D21.tif

2026-10-21 23:54:23,906 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x56y441_NV_EastCentral_2021_D21.tif (263.53 MB)
2026-10-21 23:54:23,958 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x56y442_NV_EastCentral_2021_D21.tif

DEM 813/894: USGS_1M_11_x56y442_NV_EastCentral_2021_D21.tif

2026-10-21 23:54:37,257 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x56y442_NV_EastCentral_2021_D21.tif (265.97 MB)
2026-10-21 23:54:37,314 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x56y443_NV_EastCentral_2021_D21.tif

DEM 814/894: USGS_1M_11_x56y443_NV_EastCentral_2021_D21.tif

2026-10-21 23:54:51,954 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x56y443_NV_EastCentral_2021_D21.tif (273.62 MB)
2026-10-21 23:54:52,005 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x56y444_NV_EastCentral_2021_D21.tif

DEM 815/894: USGS_1M_11_x56y444_NV_EastCentral_2021_D21.tif

2026-10-21 23:54:53,453 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x56y444_NV_EastCentral_2021_D21.tif (23.72 MB)
2026-10-21 23:54:53,465 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y444_NV_NorthWestElko_2020_D20.tif

DEM 816/894: USGS_1M_11_x56y444_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:55:10,432 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y444_NV_NorthWestElko_2020_D20.tif (242.22 MB)
2026-10-21 23:55:10,478 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y445_NV_NorthWestElko_2020_D20.tif

DEM 817/894: USGS_1M_11_x56y445_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:55:30,619 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y445_NV_NorthWestElko_2020_D20.tif (263.07 MB)
2026-10-21 23:55:30,694 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y446_NV_NorthWestElko_2020_D20.tif

DEM 818/894: USGS_1M_11_x56y446_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:55:55,444 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y446_NV_NorthWestElko_2020_D20.tif (262.06 MB)
2026-10-21 23:55:55,527 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y447_NV_NorthWestElko_2020_D20.tif

DEM 819/894: USGS_1M_11_x56y447_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:56:12,613 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y447_NV_NorthWestElko_2020_D20.tif (271.63 MB)
2026-10-21 23:56:12,682 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y448_NV_NorthWestElko_2020_D20.tif

DEM 820/894: USGS_1M_11_x56y448_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:56:27,219 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y448_NV_NorthWestElko_2020_D20.tif (274.47 MB)
2026-10-21 23:56:27,314 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y449_NV_NorthWestElko_2020_D20.tif

DEM 821/894: USGS_1M_11_x56y449_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:56:44,574 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y449_NV_NorthWestElko_2020_D20.tif (272.93 MB)
2026-10-21 23:56:44,634 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y450_NV_NorthWestElko_2020_D20.tif

DEM 822/894: USGS_1M_11_x56y450_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:57:00,476 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y450_NV_NorthWestElko_2020_D20.tif (290.04 MB)
2026-10-21 23:57:00,534 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y451_NV_NorthWestElko_2020_D20.tif

DEM 823/894: USGS_1M_11_x56y451_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:57:18,660 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x56y451_NV_NorthWestElko_2020_D20.tif (279.80 MB)
2026-10-21 23:57:18,722 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y442_NV_EastCentral_2021_D21.tif

DEM 824/894: USGS_1M_11_x57y442_NV_EastCentral_2021_D21.tif

2026-10-21 23:57:33,436 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y442_NV_EastCentral_2021_D21.tif (273.21 MB)
2026-10-21 23:57:33,514 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y443_NV_EastCentral_2021_D21.tif

DEM 825/894: USGS_1M_11_x57y443_NV_EastCentral_2021_D21.tif

2026-10-21 23:57:46,073 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y443_NV_EastCentral_2021_D21.tif (270.04 MB)
2026-10-21 23:57:46,174 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y444_NV_EastCentral_2021_D21.tif

DEM 826/894: USGS_1M_11_x57y444_NV_EastCentral_2021_D21.tif

2026-10-21 23:57:53,470 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y444_NV_EastCentral_2021_D21.tif (187.26 MB)
2026-10-21 23:57:53,568 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y444_NV_NorthWestElko_2020_D20.tif

DEM 827/894: USGS_1M_11_x57y444_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:57:57,702 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y444_NV_NorthWestElko_2020_D20.tif (83.72 MB)
2026-10-21 23:57:57,743 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y445_NV_EastCentral_2021_D21.tif

DEM 828/894: USGS_1M_11_x57y445_NV_EastCentral_2021_D21.tif

2026-10-21 23:58:08,977 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y445_NV_EastCentral_2021_D21.tif (189.74 MB)
2026-10-21 23:58:09,018 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y445_NV_NorthWestElko_2020_D20.tif

DEM 829/894: USGS_1M_11_x57y445_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:58:15,819 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y445_NV_NorthWestElko_2020_D20.tif (87.31 MB)
2026-10-21 23:58:15,857 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y446_NV_EastCentral_2021_D21.tif

DEM 830/894: USGS_1M_11_x57y446_NV_EastCentral_2021_D21.tif

2026-10-21 23:58:30,278 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y446_NV_EastCentral_2021_D21.tif (188.07 MB)
2026-10-21 23:58:30,345 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y446_NV_NorthWestElko_2020_D20.tif

DEM 831/894: USGS_1M_11_x57y446_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:58:36,754 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y446_NV_NorthWestElko_2020_D20.tif (81.38 MB)
2026-10-21 23:58:36,774 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y447_NV_EastCentral_2021_D21.tif

DEM 832/894: USGS_1M_11_x57y447_NV_EastCentral_2021_D21.tif

2026-10-21 23:58:50,587 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y447_NV_EastCentral_2021_D21.tif (190.64 MB)
2026-10-21 23:58:50,632 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y447_NV_NorthWestElko_2020_D20.tif

DEM 833/894: USGS_1M_11_x57y447_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:58:55,880 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y447_NV_NorthWestElko_2020_D20.tif (81.74 MB)
2026-10-21 23:58:55,906 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y448_NV_EastCentral_2021_D21.tif

DEM 834/894: USGS_1M_11_x57y448_NV_EastCentral_2021_D21.tif

2026-10-21 23:59:07,178 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y448_NV_EastCentral_2021_D21.tif (192.62 MB)
2026-10-21 23:59:07,220 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y448_NV_NorthWestElko_2020_D20.tif

DEM 835/894: USGS_1M_11_x57y448_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:59:12,094 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y448_NV_NorthWestElko_2020_D20.tif (81.05 MB)
2026-10-21 23:59:12,115 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y449_NV_EastCentral_2021_D21.tif

DEM 836/894: USGS_1M_11_x57y449_NV_EastCentral_2021_D21.tif

2026-10-21 23:59:24,147 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y449_NV_EastCentral_2021_D21.tif (205.30 MB)
2026-10-21 23:59:24,220 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y449_NV_NorthWestElko_2020_D20.tif

DEM 837/894: USGS_1M_11_x57y449_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:59:28,257 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y449_NV_NorthWestElko_2020_D20.tif (86.06 MB)
2026-10-21 23:59:28,280 | INFO | DOWNLOADING | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y450_NV_EastCentral_2021_D21.tif

DEM 838/894: USGS_1M_11_x57y450_NV_EastCentral_2021_D21.tif

2026-10-21 23:59:35,953 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_EastCentral_2021_D21/USGS_1M_11_x57y450_NV_EastCentral_2021_D21.tif (157.40 MB)
2026-10-21 23:59:36,002 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y450_NV_NorthWestElko_2020_D20.tif

DEM 839/894: USGS_1M_11_x57y450_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:59:40,109 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y450_NV_NorthWestElko_2020_D20.tif (85.09 MB)
2026-10-21 23:59:40,133 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y451_NV_NorthWestElko_2020_D20.tif

DEM 840/894: USGS_1M_11_x57y451_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:59:43,266 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y451_NV_NorthWestElko_2020_D20.tif (73.90 MB)
2026-10-21 23:59:43,286 | INFO | DOWNLOADING | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y452_NV_NorthWestElko_2020_D20.tif

DEM 841/894: USGS_1M_11_x57y452_NV_NorthWestElko_2020_D20.tif

2026-10-21 23:59:45,358 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_NorthWestElko_2020_D20/USGS_1M_11_x57y452_NV_NorthWestElko_2020_D20.tif (33.54 MB)
2026-10-21 23:59:45,382 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x24y440_NV_Reno_Carson_QL1_2017.tif

DEM 842/894: USGS_one_meter_x24y440_NV_Reno_Carson_QL1_2017.tif

2026-10-21 23:59:59,260 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x24y440_NV_Reno_Carson_QL1_2017.tif (264.58 MB)
2026-10-21 23:59:59,323 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x24y440_NV_Reno_Carson_QL2_2017.tif

DEM 843/894: USGS_one_meter_x24y440_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:00:07,439 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x24y440_NV_Reno_Carson_QL2_2017.tif (82.02 MB)
2026-10-22 00:00:07,620 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x24y441_NV_Reno_Carson_QL2_2017.tif

DEM 844/894: USGS_one_meter_x24y441_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:00:29,994 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x24y441_NV_Reno_Carson_QL2_2017.tif (335.89 MB)
2026-10-22 00:00:30,063 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x24y442_NV_Reno_Carson_QL2_2017.tif

DEM 845/894: USGS_one_meter_x24y442_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:00:43,116 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x24y442_NV_Reno_Carson_QL2_2017.tif (261.84 MB)
2026-10-22 00:00:43,164 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x25y438_NV_Reno_Carson_QL1_2017.tif

DEM 846/894: USGS_one_meter_x25y438_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:01:03,846 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x25y438_NV_Reno_Carson_QL1_2017.tif (426.62 MB)
2026-10-22 00:01:03,906 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x25y439_NV_Reno_Carson_QL1_2017.tif

DEM 847/894: USGS_one_meter_x25y439_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:02:24,514 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x25y439_NV_Reno_Carson_QL1_2017.tif (425.22 MB)
2026-10-22 00:02:24,619 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x25y439_NV_Reno_Carson_QL2_2017.tif

DEM 848/894: USGS_one_meter_x25y439_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:02:25,754 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x25y439_NV_Reno_Carson_QL2_2017.tif (20.34 MB)
2026-10-22 00:02:25,771 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x25y440_NV_Reno_Carson_QL1_2017.tif

DEM 849/894: USGS_one_meter_x25y440_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:02:37,523 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x25y440_NV_Reno_Carson_QL1_2017.tif (215.02 MB)
2026-10-22 00:02:37,584 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x25y440_NV_Reno_Carson_QL2_2017.tif

DEM 850/894: USGS_one_meter_x25y440_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:02:47,020 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x25y440_NV_Reno_Carson_QL2_2017.tif (186.47 MB)
2026-10-22 00:02:47,057 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x25y441_NV_Reno_Carson_QL2_2017.tif

DEM 851/894: USGS_one_meter_x25y441_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:03:08,146 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x25y441_NV_Reno_Carson_QL2_2017.tif (443.25 MB)
2026-10-22 00:03:08,226 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x25y442_NV_Reno_Carson_QL2_2017.tif

DEM 852/894: USGS_one_meter_x25y442_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:03:23,622 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x25y442_NV_Reno_Carson_QL2_2017.tif (342.87 MB)
2026-10-22 00:03:23,693 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x26y437_NV_Reno_Carson_QL1_2017.tif

DEM 853/894: USGS_one_meter_x26y437_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:03:37,341 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x26y437_NV_Reno_Carson_QL1_2017.tif (264.64 MB)
2026-10-22 00:03:37,418 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x26y437_NV_Reno_Carson_QL2_2017.tif

DEM 854/894: USGS_one_meter_x26y437_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:03:45,983 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x26y437_NV_Reno_Carson_QL2_2017.tif (184.14 MB)
2026-10-22 00:03:46,028 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x26y438_NV_Reno_Carson_QL1_2017.tif

DEM 855/894: USGS_one_meter_x26y438_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:04:00,715 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x26y438_NV_Reno_Carson_QL1_2017.tif (272.74 MB)
2026-10-22 00:04:00,808 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x26y438_NV_Reno_Carson_QL2_2017.tif

DEM 856/894: USGS_one_meter_x26y438_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:04:08,815 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x26y438_NV_Reno_Carson_QL2_2017.tif (149.37 MB)
2026-10-22 00:04:08,899 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x26y439_NV_Reno_Carson_QL1_2017.tif

DEM 857/894: USGS_one_meter_x26y439_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:04:29,822 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x26y439_NV_Reno_Carson_QL1_2017.tif (379.16 MB)
2026-10-22 00:04:29,919 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x26y439_NV_Reno_Carson_QL2_2017.tif

DEM 858/894: USGS_one_meter_x26y439_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:04:31,703 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x26y439_NV_Reno_Carson_QL2_2017.tif (47.96 MB)
2026-10-22 00:04:31,717 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x26y440_NV_Reno_Carson_QL1_2017.tif

DEM 859/894: USGS_one_meter_x26y440_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:04:36,531 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x26y440_NV_Reno_Carson_QL1_2017.tif (146.87 MB)
2026-10-22 00:04:36,602 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x26y440_NV_Reno_Carson_QL2_2017.tif

DEM 860/894: USGS_one_meter_x26y440_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:04:51,175 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x26y440_NV_Reno_Carson_QL2_2017.tif (297.53 MB)
2026-10-22 00:04:51,247 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x26y441_NV_Reno_Carson_QL2_2017.tif

DEM 861/894: USGS_one_meter_x26y441_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:05:10,443 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x26y441_NV_Reno_Carson_QL2_2017.tif (442.00 MB)
2026-10-22 00:05:10,559 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x26y442_NV_Reno_Carson_QL2_2017.tif

DEM 862/894: USGS_one_meter_x26y442_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:05:26,772 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x26y442_NV_Reno_Carson_QL2_2017.tif (330.64 MB)
2026-10-22 00:05:26,838 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x27y435_NV_Reno_Carson_QL1_2017.tif

DEM 863/894: USGS_one_meter_x27y435_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:05:46,597 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x27y435_NV_Reno_Carson_QL1_2017.tif (359.72 MB)
2026-10-22 00:05:46,657 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y435_NV_Reno_Carson_QL2_2017.tif

DEM 864/894: USGS_one_meter_x27y435_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:05:49,707 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y435_NV_Reno_Carson_QL2_2017.tif (89.80 MB)
2026-10-22 00:05:49,729 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x27y436_NV_Reno_Carson_QL1_2017.tif

DEM 865/894: USGS_one_meter_x27y436_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:06:03,823 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x27y436_NV_Reno_Carson_QL1_2017.tif (252.32 MB)
2026-10-22 00:06:03,885 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y436_NV_Reno_Carson_QL2_2017.tif

DEM 866/894: USGS_one_meter_x27y436_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:06:16,769 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y436_NV_Reno_Carson_QL2_2017.tif (240.19 MB)
2026-10-22 00:06:16,831 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y437_NV_Reno_Carson_QL2_2017.tif

DEM 867/894: USGS_one_meter_x27y437_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:06:43,084 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y437_NV_Reno_Carson_QL2_2017.tif (449.20 MB)
2026-10-22 00:06:43,161 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y438_NV_Reno_Carson_QL2_2017.tif

DEM 868/894: USGS_one_meter_x27y438_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:07:06,193 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y438_NV_Reno_Carson_QL2_2017.tif (460.45 MB)
2026-10-22 00:07:06,285 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x27y439_NV_Reno_Carson_QL1_2017.tif

DEM 869/894: USGS_one_meter_x27y439_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:07:07,702 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x27y439_NV_Reno_Carson_QL1_2017.tif (31.36 MB)
2026-10-22 00:07:07,712 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y439_NV_Reno_Carson_QL2_2017.tif

DEM 870/894: USGS_one_meter_x27y439_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:07:30,405 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y439_NV_Reno_Carson_QL2_2017.tif (429.74 MB)
2026-10-22 00:07:30,539 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x27y440_NV_Reno_Carson_QL1_2017.tif

DEM 871/894: USGS_one_meter_x27y440_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:07:34,653 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x27y440_NV_Reno_Carson_QL1_2017.tif (101.75 MB)
2026-10-22 00:07:34,681 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y440_NV_Reno_Carson_QL2_2017.tif

DEM 872/894: USGS_one_meter_x27y440_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:07:50,870 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y440_NV_Reno_Carson_QL2_2017.tif (333.88 MB)
2026-10-22 00:07:50,920 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y441_NV_Reno_Carson_QL2_2017.tif

DEM 873/894: USGS_one_meter_x27y441_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:08:06,909 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y441_NV_Reno_Carson_QL2_2017.tif (394.73 MB)
2026-10-22 00:08:07,000 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y442_NV_Reno_Carson_QL2_2017.tif

DEM 874/894: USGS_one_meter_x27y442_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:08:20,773 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x27y442_NV_Reno_Carson_QL2_2017.tif (292.62 MB)
2026-10-22 00:08:20,832 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x28y435_NV_Reno_Carson_QL1_2017.tif

DEM 875/894: USGS_one_meter_x28y435_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:08:32,577 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x28y435_NV_Reno_Carson_QL1_2017.tif (249.88 MB)
2026-10-22 00:08:32,624 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x28y436_NV_Reno_Carson_QL1_2017.tif

DEM 876/894: USGS_one_meter_x28y436_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:08:45,219 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x28y436_NV_Reno_Carson_QL1_2017.tif (247.53 MB)
2026-10-22 00:08:45,270 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x28y436_NV_Reno_Carson_QL2_2017.tif

DEM 877/894: USGS_one_meter_x28y436_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:08:48,163 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x28y436_NV_Reno_Carson_QL2_2017.tif (66.94 MB)
2026-10-22 00:08:48,181 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x28y437_NV_Reno_Carson_QL2_2017.tif

DEM 878/894: USGS_one_meter_x28y437_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:09:12,731 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x28y437_NV_Reno_Carson_QL2_2017.tif (462.94 MB)
2026-10-22 00:09:12,795 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x28y438_NV_Reno_Carson_QL2_2017.tif

DEM 879/894: USGS_one_meter_x28y438_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:09:36,447 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x28y438_NV_Reno_Carson_QL2_2017.tif (465.94 MB)
2026-10-22 00:09:36,524 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x28y439_NV_Reno_Carson_QL2_2017.tif

DEM 880/894: USGS_one_meter_x28y439_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:09:56,793 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x28y439_NV_Reno_Carson_QL2_2017.tif (416.86 MB)
2026-10-22 00:09:56,860 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x29y436_NV_Reno_Carson_QL2_2017.tif

DEM 881/894: USGS_one_meter_x29y436_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:09:58,228 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x29y436_NV_Reno_Carson_QL2_2017.tif (36.80 MB)
2026-10-22 00:09:58,242 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x29y437_NV_Reno_Carson_QL2_2017.tif

DEM 882/894: USGS_one_meter_x29y437_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:10:10,069 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x29y437_NV_Reno_Carson_QL2_2017.tif (252.36 MB)
2026-10-22 00:10:10,149 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x29y438_NV_Reno_Carson_QL2_2017.tif

DEM 883/894: USGS_one_meter_x29y438_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:10:24,678 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x29y438_NV_Reno_Carson_QL2_2017.tif (271.39 MB)
2026-10-22 00:10:24,749 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x29y439_NV_Reno_Carson_QL2_2017.tif

DEM 884/894: USGS_one_meter_x29y439_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:10:38,766 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x29y439_NV_Reno_Carson_QL2_2017.tif (255.93 MB)
2026-10-22 00:10:38,818 | INFO | DOWNLOADING | data/raw/dem_1m/NV_UpperHumboldt_2016/USGS_one_meter_x57y450_NV_UpperHumboldt_2016.tif

DEM 885/894: USGS_one_meter_x57y450_NV_UpperHumboldt_2016.tif

2026-10-22 00:10:44,541 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_UpperHumboldt_2016/USGS_one_meter_x57y450_NV_UpperHumboldt_2016.tif (94.49 MB)
2026-10-22 00:10:44,565 | INFO | DOWNLOADING | data/raw/dem_1m/NV_UpperHumboldt_2016/USGS_one_meter_x57y451_NV_UpperHumboldt_2016.tif

DEM 886/894: USGS_one_meter_x57y451_NV_UpperHumboldt_2016.tif

2026-10-22 00:11:05,625 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_UpperHumboldt_2016/USGS_one_meter_x57y451_NV_UpperHumboldt_2016.tif (376.49 MB)
2026-10-22 00:11:05,677 | INFO | DOWNLOADING | data/raw/dem_1m/NV_UpperHumboldt_2016/USGS_one_meter_x57y452_NV_UpperHumboldt_2016.tif

DEM 887/894: USGS_one_meter_x57y452_NV_UpperHumboldt_2016.tif

2026-10-22 00:11:23,504 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_UpperHumboldt_2016/USGS_one_meter_x57y452_NV_UpperHumboldt_2016.tif (370.47 MB)
2026-10-22 00:11:23,589 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x75y441_NV_Reno_Carson_QL2_2017.tif

DEM 888/894: USGS_one_meter_x75y441_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:11:29,754 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x75y441_NV_Reno_Carson_QL2_2017.tif (156.44 MB)
2026-10-22 00:11:29,815 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x75y442_NV_Reno_Carson_QL2_2017.tif

DEM 889/894: USGS_one_meter_x75y442_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:11:36,644 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x75y442_NV_Reno_Carson_QL2_2017.tif (140.92 MB)
2026-10-22 00:11:36,760 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x76y439_NV_Reno_Carson_QL1_2017.tif

DEM 890/894: USGS_one_meter_x76y439_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:12:07,247 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x76y439_NV_Reno_Carson_QL1_2017.tif (452.74 MB)
2026-10-22 00:12:07,306 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x76y440_NV_Reno_Carson_QL1_2017.tif

DEM 891/894: USGS_one_meter_x76y440_NV_Reno_Carson_QL1_2017.tif

2026-10-22 00:12:24,366 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL1_2017/USGS_one_meter_x76y440_NV_Reno_Carson_QL1_2017.tif (336.82 MB)
2026-10-22 00:12:24,470 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x76y440_NV_Reno_Carson_QL2_2017.tif

DEM 892/894: USGS_one_meter_x76y440_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:12:27,541 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x76y440_NV_Reno_Carson_QL2_2017.tif (77.00 MB)
2026-10-22 00:12:27,565 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x76y441_NV_Reno_Carson_QL2_2017.tif

DEM 893/894: USGS_one_meter_x76y441_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:12:47,384 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x76y441_NV_Reno_Carson_QL2_2017.tif (447.02 MB)
2026-10-22 00:12:47,464 | INFO | DOWNLOADING | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x76y442_NV_Reno_Carson_QL2_2017.tif

DEM 894/894: USGS_one_meter_x76y442_NV_Reno_Carson_QL2_2017.tif

2026-10-22 00:13:04,022 | INFO | SAVED TO DRIVE | data/raw/dem_1m/NV_Reno_Carson_QL2_2017/USGS_one_meter_x76y442_NV_Reno_Carson_QL2_2017.tif (381.78 MB)

DEM downloaded/reused: 140
DEM failures: 754
Failure report: /content/drive/MyDrive/GEMS_2/data/manifests/dem_failures.csv

DATA COLLECTION COMPLETE
Drive root: /content/drive/MyDrive/GEMS_2
Total cached files: 380
Total cached GB: 82.48
Manifest: /content/drive/MyDrive/GEMS_2/data/manifests/download_manifest.json

In [3]:
# Optional: USGS TNM 1 m DEM URL list for the study area via the TNM Access API (metadata only: NO tiles here;
# tiles are downloaded later by notebook 05 after explicit approval). Skip if you already have your own JSON.
FETCH_DEM_URL_LIST = False
dem_json = Path(DRIVE_ROOT) / 'data/raw/dem_1m/tnm_urls.json'
if FETCH_DEM_URL_LIST and not dem_json.exists():
    import json, urllib.parse
    import rasterio
    from rasterio.warp import transform_bounds
    with rasterio.open(LOCAL / 'data/raw/geodawn/gems-geodawn-numerical-features.tif') as src:
        w, s, e, n = transform_bounds(src.crs, 'EPSG:4326', *src.bounds)
    items, offset = [], 0
    while True:
        q = urllib.parse.urlencode({'datasets': 'Digital Elevation Model (DEM) 1 meter', 'prodFormats': 'GeoTIFF',
                                    'bbox': f'{w:.4f},{s:.4f},{e:.4f},{n:.4f}', 'max': 500, 'offset': offset})
        page = LOCAL / f'data/raw/dem_1m/_tnm_page_{offset}.json'
        page.unlink(missing_ok=True)                  # a page must never be "continued" by wget -c
        wget('https://tnmaccess.nationalmap.gov/api/v1/products?' + q, page)
        r = json.loads(page.read_text())
        items += r.get('items', [])
        offset += 500
        if offset >= int(r.get('total', 0)) or not r.get('items'):
            break
    out = LOCAL / 'data/raw/dem_1m/tnm_urls.json'
    out.write_text(json.dumps({'items': items, 'bbox_wgs84': [w, s, e, n]}, indent=1))
    for p in out.parent.glob('_tnm_page_*.json'):
        p.unlink()
    gib = sum(i.get('sizeInBytes') or 0 for i in items) / 2**30
    print(f'{len(items)} products listed ({gib:.1f} GiB if ALL were downloaded - the pilot uses ~24 tiles)')
    colab.sync().push(['data/raw/dem_1m/tnm_urls.json'])
elif dem_json.exists():
    print('DEM URL list on Drive:', dem_json)

In [4]:
# PyTorch / GPU and the auto-configuration the trainers will use
from gems_bench.training import gpu
g = gpu.detect()
print(g)
print('autoconfig (256 px, effective batch 16, 29 channels):', gpu.autoconfig(g, patch_px=256, effective_batch=16, n_channels=29))

{'cuda': False, 'name': None, 'vram_gb': 0.0, 'capability': None, 'count': 0}
autoconfig (256 px, effective batch 16, 29 channels): {'amp': False, 'data_on_gpu': False, 'batch_size': 4, 'grad_accum': 4, 'infer_batch': 4, 'cudnn_benchmark': False}

In [5]:
# Drive layout: create missing workspace folders on Drive and locally (never deletes anything)
from pathlib import Path
from gems_bench.paths import WORKSPACE_DIRS
for d in WORKSPACE_DIRS:
    (Path(DRIVE_ROOT) / d).mkdir(parents=True, exist_ok=True)
    (Path(colab.LOCAL_ROOT) / d).mkdir(parents=True, exist_ok=True)
required = ['data/raw/geodawn/gems-geodawn-numerical-features.tif', 'data/raw/faults/existing_faults.tif',
            'data/raw/geodawn/example_submission.tif', 'outputs/benchmark/folds', 'outputs/phase4/experiments']
for r in required:
    print(('OK      ' if (Path(DRIVE_ROOT) / r).exists() else 'MISSING ') + r)
print('See docs/GOOGLE_DRIVE_LAYOUT.md for what to upload once from the local project.')

OK      data/raw/geodawn/gems-geodawn-numerical-features.tif
OK      data/raw/faults/existing_faults.tif
MISSING data/raw/geodawn/example_submission.tif
MISSING outputs/benchmark/folds
MISSING outputs/phase4/experiments
See docs/GOOGLE_DRIVE_LAYOUT.md for what to upload once from the local project.

In [6]:
# Stage the core data to the fast local disk (unchanged files are skipped on later sessions)
staged = colab.stage_core()
staged.groupby('action').bytes.agg(['count', 'sum'])

[stage] not on Drive (see docs/GOOGLE_DRIVE_LAYOUT.md): ['outputs/benchmark/folds', 'outputs/benchmark/datasets', 'outputs/eda/manifest.json', 'outputs/eda/datasets']
[sync in] 2 copied (399.9 MiB), 0 unchanged, 11s: ['data/raw/geodawn', 'data/raw/faults', 'experiments', 'model_registry']

        count        sum
action
copy        2  419338674

In [7]:
# Existing experiment manifests and the model registry (from Drive)
import json
import pandas as pd
from gems_bench.artifacts import ModelRegistry
rows = []
for m in sorted(Path(DRIVE_ROOT, 'experiments').glob('*/manifest.json')):
    j = json.loads(m.read_text())
    rows.append({'experiment': j['experiment_id'], 'kind': j['kind'], 'commit': j.get('git_commit', '')[:10],
                 **{s: v['status'] for s, v in j['stages'].items()}})
display(pd.DataFrame(rows))
display(ModelRegistry(Path(DRIVE_ROOT) / 'model_registry').table())

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: [name, status, kind, experiment_id, oof, discovery, config_hash, git_commit, geo_dti, disc_dti_excl, disc_dti_retained_fp, protocol_hash, updated, notes]
Index: []

In [8]:
colab.environment_report()

,key,value
0,package,gems-fault-discovery
1,version,0.5.0
2,git_commit,32c0ad518fc375fdd872424a2a78503d54def93f
3,python,3.13.16
4,gpu,None
5,vram_gb,0.0
6,capability,None
7,torch,2.11.0+cpu
8,cuda,None
9,free_gb:/content,173.9
10,free_gb:/content/drive/MyDrive/GEMS_2,165.2
11,GEMS_ROOT,/content/gems_work
12,GEMS_DRIVE_ROOT,/content/drive/MyDrive/GEMS_2
13,GEMS_CODE_ROOT,/content/GEMS